BastionOfEndeavor/BastionOfEndeavor2

- code/modules/admin/verbs/adminjump.dm
> [CH] Fix adminjump

- modular_chomp/code/game/turfs/turfpacks/unsim_turfs/unsim_turfs.dm
> [CH] Mistake in turfpacks

- code/modules/research/rdconsole.dm
- code/modules/research/rdconsole_tgui.dm
- modular_chomp/code/modules/research/rdconsole.dm
- tgui/packages/tgui/interfaces/ResearchConsole.jsx
> [VR]  adds an option for non-synced consoles

- code/_helpers/logging.dm
> [CH] make LANGSANI debug dependent

- code/__defines/atoms_movable.dm
- code/datums/observation/moved.dm
- code/game/atoms_movable.dm
- code/modules/mob/dead/observer/observer.dm
> [CH] Smoothens ghost following

- code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
> [CH] fix darkmaw

- code/game/gamemodes/technomancer/spells/spawner/pulsar.dm
- code/modules/entopics_vr/alternate_appearance.dm
- code/modules/mob/freelook/ai/eye.dm
- code/modules/mob/living/simple_mob/life.dm
- code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/broodmother_spawn.dm
- code/modules/mob/mob.dm
> [CH] Several harddels/runtimes

- code/global.dm
> [VR]  Fixes issue#15869 (RD not having access to department funds

- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
> [CH] Protean blob fix

- tgui/packages/tgui/interfaces/ResearchConsole.jsx
> [VR]  rdconsole design fix

- code/game/machinery/portable_turret.dm
- code/modules/blob2/overmind/powers.dm
- modular_chomp/code/game/machinery/portable_turret.dm
> [CH] changes of #5442

- code/__defines/statpanel_ch.dm
- code/_helpers/icons.dm
- code/controllers/subsystems/statpanel_ch.dm
- code/modules/asset_cache/assets/tgfont.dm
- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
- code/modules/mob/living/simple_mob/subtypes/vore/shadekin/shadekin.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
- vorestation.dme
> [CH] TGPanel Patch 1

- config/jukebox.json
> [CH] Update jukebox.json

- code/modules/events/dust.dm
- code/modules/mob/living/silicon/laws.dm
- modular_chomp/code/modules/event/event_container_ch.dm
> [CH] Enables events disabled in YW

- code/modules/vore/mouseray.dm
> [CH] Add catslug to basic metamorphosis ray

- code/_helpers/text.dm
> [CH] Different chat icon tag method

- code/controllers/failsafe.dm
- code/game/birthday.dm
- code/game/jobs/whitelist.dm
- code/game/jobs/whitelist_vr.dm
- code/game/objects/effects/landmarks.dm
- code/game/turfs/flooring/seasonal.dm
- code/game/turfs/simulated/floor_icon.dm
- code/modules/client/preference_setup/loadout/loadout.dm
- code/modules/events/roaming_wildlife.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/simple_mob/subtypes/animal/squirrel.dm
- code/modules/mob/login_ch.dm
- code/modules/mob/mob.dm
- modular_chomp/code/game/objects/effects/step_triggers.dm
- modular_chomp/code/global.dm
- modular_chomp/code/modules/admin/verbs/randomverbs.dm
- modular_chomp/code/modules/client/preference_setup/loadout/gear_tweaks.dm
- modular_chomp/code/modules/client/preferences_spawnpoints.dm
- modular_chomp/code/modules/event/meatyores.dm
- modular_chomp/code/modules/flufftext/Dreaming.dm
- modular_chomp/code/modules/recycling/v_garbosystem.dm
> [CH] Properly defines a few global vars

- code/_helpers/mobs.dm
- code/game/machinery/portable_turret.dm
- code/game/sound.dm
- modular_chomp/code/game/machinery/portable_turret.dm
> [CH] various optimizations

- code/controllers/subsystems/assets.dm
> [CH] fix chat tag shenanigans

- code/modules/surgery/surgery.dm
> [CH] fix missing target in a balloon alert

- code/game/mecha/equipment/mecha_equipment.dm
- code/game/mecha/mecha.dm
> [CH] fixces 2 mech runtimes

- config/jukebox.json
> [CH] Minor edit to jukebox.json

- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/bellymodes_datum_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyOptions.tsx
> [CH] custom egg size

- code/_helpers/time.dm
- code/game/world.dm
> [CH] Time tweak again

- code/__defines/admin_vr.dm
- code/modules/admin/verbs/modify_robot.dm
> [VR]  some more borg admin options

- code/modules/mob/living/silicon/ai/ai_remote_control.dm
- code/modules/mob/living/silicon/robot/robot_remote_control.dm
> [VR]  copy ai bellies onn first transfer and keep prefs synced

- tgui/packages/tgui-panel/chat/middleware.js
- tgui/packages/tgui-panel/chat/renderer.jsx
- tgui/packages/tgui-panel/settings/SettingsPanel.jsx
- tgui/packages/tgui-panel/settings/reducer.js
> [VR]  allows to interleave chat messages

- code/modules/mob/living/simple_mob/subtypes/vore/pakkun.dm
> [VR]  Makes pakkuns less triggerhappy, more sneaky

- code/controllers/subsystems/verb_manager_ch.dm
> [CH] Fixes the verb manager based stat entries to show

- maps/redgate/eggnogtownunderground.dmm
> [VR]  Quick Radio Fix for Eggnog Town (Attempt 2)

- code/game/jobs/job/exploration_vr.dm
> [CH] adds explorer access to pilots and field medics

- code/modules/mob/living/default_language.dm
> [CH] fix language selection verb

- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
- code/modules/mob/living/living_defense.dm
- code/modules/planet/virgo3c_vr.dm
- code/modules/vore/eating/living_ch.dm
- code/modules/vore/eating/living_vr.dm
> [VR]  Ports trash throw vore from Chomp

- code/modules/mob/living/silicon/robot/sprites/civilian.dm
> [VR]  enables vorsrprites on service tallbots

- code/modules/vore/eating/living_vr.dm
> [CH] Makes the trash eat message ambigious.

- code/modules/mob/living/default_language.dm
> [CH] robot language selection fix

- code/modules/mob/living/silicon/robot/robot.dm
> [CH] small cleanup

- code/__defines/belly_modes_vr.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/living_defines.dm
- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/bellymodes_vr.dm
- code/modules/vore/eating/living_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- tgui/packages/tgui/interfaces/VorePanel.jsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyOptions.tsx
> [VR]  Added Post-Drain belly modes

- code/modules/shieldgen/shield_diffuser.dm
- code/modules/shieldgen/shield_gen.dm
> [CH] Shield diffusers gets disabled with meteors

- code/modules/client/preference_setup/loadout/loadout_utility_vr.dm
> [VR]  Reduces the cost of the bluespace bracelet.

- code/modules/mob/living/simple_mob/simple_mob.dm
- code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
> [VR]  Gives simple mobs thermals

- code/modules/mob/living/simple_mob/simple_mob.dm
> [CH] Fix bad verb i missed

- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/living.dm
> [CH] adds pain overhealth check

- code/modules/shieldgen/shield_gen.dm
> [CH] Allows point defense to bypass the diffuser alarms

- code/modules/mob/living/say.dm
> [CH] Allow speech sounds to pass walls

- code/modules/shieldgen/shield_diffuser.dm
- code/modules/shieldgen/shield_gen.dm
> [CH] Undo meteor shield changes

- tools/requirements.txt
> [CH] Bump pillow from 10.2.0 to 10.3.0 in /tools

- maps/southern_cross/southern_cross-1.dmm
- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/southern_cross-3.dmm
> [CH] [Deck 1/2/3] SC Maints+

- code/defines/procs/announce.dm
- code/modules/events/spacevine.dm
- code/modules/events/viral_infection.dm
- code/modules/events/viral_outbreak.dm
- code/modules/events/wallrot.dm
- code/modules/gamemaster/event2/events/engineering/blob.dm
- code/modules/gamemaster/event2/events/engineering/spacevine.dm
- code/modules/gamemaster/event2/events/medical/virus.dm
- modular_chomp/code/modules/event/infectedroom.dm
> [CH] Confirmed outbreak of a less stupid biohazard system

- code/modules/power/supermatter/supermatter.dm
> [CH] Make SM alarm reset a global

- code/game/machinery/telecomms/machine_interactions.dm
- code/modules/asset_cache/asset_list_items.dm
- code/modules/tgui/modules/atmos_control.dm
- code/modules/tgui/modules/crew_monitor.dm
- maps/~map_system/maps.dm
- tgui/packages/tgui/components/NanoMap.jsx
- tgui/packages/tgui/interfaces/AtmosControl.jsx
- tgui/packages/tgui/interfaces/CrewMonitor.jsx
- tgui/packages/tgui/interfaces/TelecommsMultitoolMenu.jsx
> [CH] map view fixes and tcomms

- maps/southern_cross/southern_cross-1.dmm
> [CH] Crystals Moved

- code/ATMOSPHERICS/components/omni_devices/filter.dm
- code/ATMOSPHERICS/components/omni_devices/mixer.dm
- tgui/packages/tgui/interfaces/OmniFilter.tsx
- tgui/packages/tgui/interfaces/OmniMixer.tsx
> [CH] fix omni atmospherics tgui

- code/game/turfs/simulated/outdoors/grass.dm
- maps/southern_cross/southern_cross-3.dmm
- modular_chomp/code/modules/emotes/definitions/audiable.dm
> [CH] Grass runtime fix / bad emote / Deck 3 errors

- tools/github-actions/README.MD
- tools/github-actions/nanomap-renderer-invoker.sh
> [CH] Make nanomap renderer script cool again

- code/game/machinery/air_alarm.dm
- code/game/machinery/portable_turret.dm
- code/modules/power/apc.dm
- modular_chomp/code/modules/mob/living/silicon/robot/robot.dm
> [CH] Borg access

- code/game/machinery/cryopod.dm
- code/modules/food/food.dm
> [CH] Mind Binder food and cryo fixes

- code/modules/mob/living/simple_mob/subtypes/vore/solarmoth_ch.dm
> [CH] glow fix solarmoth

- maps/southern_cross/southern_cross-1.dmm
> [CH] Fixes Viro, hopefully

- code/controllers/hooks-defs.dm
> [CH] Removes some of the never called/used hooks

- code/modules/power/cell.dm
> [VR]  cell div by 0

- code/modules/mob/living/carbon/human/life.dm
> [CH] Adjust Growth/Shrink Trait

- maps/southern_cross/southern_cross-1.dmm
- maps/southern_cross/southern_cross-3.dmm
- maps/southern_cross/southern_cross_areas.dm
> [CH] SC maint fixes and adjustments.

- code/game/jobs/whitelist.dm
- code/game/jobs/whitelist_vr.dm
- code/modules/admin/admin_verb_lists_vr.dm
> [CH] Admin commands: reload job/alien whitelists

- code/game/machinery/cell_charger.dm
> [CH] makes charger icons work again

- code/modules/mob/dead/observer/observer.dm
> [CH] Deal with clients or keys on qdel of /mob/observer/dead

- code/modules/emotes/emote_mob.dm
- code/modules/mob/say_vr.dm
> [CH] Emoting and narrating voice-sounds go through walls

- code/modules/vore/mouseray.dm
> [CH] Drop items in hands on mouse ray transformation

- code/modules/mob/_modifiers/modifiers_vr.dm
- code/modules/mob/living/carbon/human/human_movement.dm
> [CH] Tweaks aquatic behavior

- code/modules/mob/living/silicon/robot/sprites/medical.dm
- modular_chomp/code/modules/mob/living/silicon/robot/sprites/civilian.dm
> [CH] cleanup some more borg stuff

- code/modules/mob/living/simple_mob/subtypes/vore/scrubble.dm
- maps/redgate/jungle.dmm
- maps/redgate/jungle_underground.dmm
> [VR]  Scrubble and jungle fixes

- maps/redgate/jungle_underground.dmm
> [VR]  Fixes broken stairs in the jungle

- code/modules/organs/organ_icon.dm
- modular_chomp/code/modules/organs/organ_icon.dm
> [CH] Limb_icon_cache tweak

- tgui/packages/tgui/interfaces/Vending.jsx
> [VR]  adds search bar to normal vendors. Fix an issue with a wrongly used key

- tgui/yarn.lock
> [CH] Bump tar from 6.2.0 to 6.2.1 in /tgui

- code/game/machinery/atmoalter/portable_atmospherics.dm
- code/game/sound.dm
- code/modules/projectiles/guns/energy.dm
> [CH] minor fixes

- code/game/machinery/cell_charger.dm
- code/modules/ai/ai_holder_combat_unseen.dm
- code/modules/examine/descriptions/guns.dm
- code/modules/hydroponics/seed.dm
- code/modules/mob/living/living_defense.dm
- code/modules/paperwork/paper_bundle.dm
- code/modules/reagents/reagent_containers/spray.dm
> [VR]  fix some runtimes and an overlay overflow

- code/controllers/subsystems/mobs.dm
- code/controllers/subsystems/plants.dm
- code/controllers/subsystems/radiation.dm
- code/game/atoms_movable.dm
- code/game/atoms_movable_ch.dm
- code/modules/projectiles/projectile.dm
- modular_chomp/code/game/objects/effects/dark_growth.dm
> [CH] GC cleanup

- code/modules/clothing/glasses/glasses_vr.dm
> [CH] Fix Tajaran veils being low on the layers

- code/modules/pda/ai.dm
- code/modules/pda/pda.dm
- code/modules/pda/pda_subtypes.dm
- code/modules/pda/pda_vr.dm
> [CH] Fix PDA option not working

- code/controllers/configuration_ch/entries/game_options.dm
- config/example/game_options.txt
> [CH] Fix config multiplier values

- code/game/area/Space Station 13 areas_ch.dm
- code/modules/events/mutants.dm
- code/modules/mob/living/simple_mob/subtypes/vore/rat_ch.dm
- maps/southern_cross/southern_cross-0.dmm
- maps/southern_cross/southern_cross_areas.dm
- modular_chomp/code/game/objects/mob_spawner.dm
- modular_chomp/code/modules/event/event_container_ch.dm
> [CH] [Deck 0] Maintenance Deck fixes and changes

- code/modules/pda/pda.dm
> [CH] unicode

- maps/offmap_vr/common_offmaps.dm
> [VR]  Redgates are no longer in space

- tools/pull_request_hooks/changelogConfig.js
> [CH] fix autochangelog not working on maptweaks

- modular_chomp/maps/overmap/space_pois/space_pois.dm
> [CH] remove server exploding submap

- code/modules/mob/living/silicon/robot/drone/drone.dm
> [CH] Comment out a round removal method

- code/__defines/_compile_options.dm
- code/datums/reference_tracking.dm
- code/datums/reference_tracking_ch.dm
- code/game/atoms_movable_ch.dm
- code/modules/ai/ai_holder_combat.dm
- vorestation.dme
> [CH] GC go brrrr

- tgui/packages/tgui-panel/chat/renderer.jsx
- tgui/packages/tgui/components/Autofocus.tsx
- tgui/packages/tgui/components/Section.tsx
- tgui/packages/tgui/components/Tabs.tsx
- tgui/packages/tgui/events.ts
- tgui/packages/tgui/interfaces/BodyDesigner.jsx
- tgui/packages/tgui/interfaces/chompstation/TicketsPanel.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreBellySelectionAndCustomization.jsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/index.tsx
- tgui/packages/tgui/layouts/Layout.tsx
> [CH] scrollingFixes

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/game/machinery/doors/firedoor.dm
- code/game/objects/structures/catwalk.dm
- code/game/objects/structures/girders.dm
- code/game/objects/structures/lattice.dm
- code/game/turfs/simulated/floor.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/space/space.dm
- code/modules/examine/descriptions/engineering.dm
- code/modules/materials/materials/_materials.dm
> [VR]  Fixes inconsistant material refunds and removes material cost from door repair

- code/modules/clothing/masks/tesh_synth_facemask.dm
> [VR]  Upport Teshari Synth Face mask from Chompstation

- code/game/objects/items_vr.dm
- code/modules/mob/language/language.dm
- code/modules/mob/living/default_language.dm
- code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/voice/voice.dm
- code/modules/virus2/effect_vr.dm
- code/modules/vore/eating/living_vr.dm
- modular_chomp/code/game/objects/items/devices/mind_binder.dm
> [CH] fix some weakened and speech issues

- code/game/objects/items/devices/translocator_vr.dm
> [CH] Translocator Noms fix

- code/modules/mob/new_player/sprite_accessories_extra_ch.dm
> [CH] finally latex (new marking)

- code/modules/clothing/clothing.dm
- code/modules/clothing/clothing_icons.dm
- code/modules/mob/living/carbon/human/update_icons.dm
> [CH] Icon access violation crash prevention attempt

- code/modules/vore/eating/living_vr.dm
> [CH] Re-add smelling phased kin

- code/game/objects/items/devices/scanners/sleevemate.dm
> [CH] undo added pref to sleevemate

- code/modules/lighting/lighting_source.dm
> [CH] hopefully silence obnoxious runtime

- modular_chomp/code/game/turfs/simulated/outdoors/valley.dm
> [CH] Temp sprite

- code/modules/mob/living/carbon/human/update_icons.dm
> [CH] Another cached icon edit

- code/game/atoms_movable.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
> [CH] Shadekin Phase Animation Size

- code/modules/mob/new_player/sprite_accessories_taur.dm
> [CH] Fixes runtime with taur-less humanmob buckling

- code/game/atoms.dm
> [CH] Make the default for blood stains being oil if no DNA is found.

- code/__defines/misc_ch.dm
- maps/southern_cross/submaps/virtual_reality/constructVR.dm
- maps/southern_cross/submaps/virtual_reality/constructVR.dmm
- modular_chomp/code/datums/outfits/jobs/noncrew.dm
- modular_chomp/code/game/jobs/job/noncrew.dm
- modular_chomp/code/modules/mob/dead/observer/observer.dm
> [CH] Gives VR avatars a custom job, Fixes duplicate PDAs, new VR roleplay room

- code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
- code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
- code/modules/mob/living/carbon/human/species/station/traits_vr/positive_ch.dm
> [VR]  Opens more positive and negative traits to non-custom species.

- code/modules/vore/eating/belly_obj_vr.dm
> [VR]  Ghosts stay in bellies

- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral_ch.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/negative.dm
> [CH] revert some changes

- code/controllers/subsystems/lighting.dm
- code/controllers/subsystems/planets.dm
- code/game/turfs/turf_changing.dm
- code/modules/lighting/lighting_fake_sun_vr.dm
- code/modules/lighting/lighting_fake_sun_zz_ch.dm
- code/modules/lighting/planet_sunlight_ch.dm
- code/modules/lighting/sunlight_handler_ch.dm
- maps/southern_cross/submaps/virtual_reality/constructVR.dm
- vorestation.dme
> [CH] lighting fixes and optimizations

- code/game/machinery/camera/tracking.dm
- code/game/objects/items/devices/communicator/communicator.dm
- code/game/objects/items/devices/spy_bug.dm
- code/modules/client/preference_setup/general/01_basic.dm
- code/modules/client/preference_setup/general/02_language.dm
- code/modules/client/preference_setup/general/03_body.dm
- code/modules/client/preference_setup/general/04_equipment.dm
- code/modules/client/preference_setup/general/05_background.dm
- code/modules/client/preference_setup/general/06_flavor.dm
- code/modules/client/preference_setup/occupation/occupation.dm
- code/modules/client/preference_setup/volume_sliders/01_volume.dm
- code/modules/client/preference_setup/volume_sliders/02_media.dm
- code/modules/client/preference_setup/vore/02_size.dm
- code/modules/client/preference_setup/vore/07_traits.dm
- code/modules/client/preferences.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_vr.dm
- code/modules/mob/living/login.dm
- code/modules/power/cable.dm
- code/modules/vore/eating/living_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/mob/living/living.dm
> [CH] Remove many incorrect uses of usr

- modular_chomp/code/game/objects/mob_spawner.dm
> [CH] Small Mining Mob Addition

- code/modules/planet/sif.dm
- modular_chomp/code/modules/planet/sif.dm
> [CH] Fixes certain firework stars from not working and nighttime changes

- code/ATMOSPHERICS/pipes/pipe_base.dm
- code/ATMOSPHERICS/pipes/pipe_base_ch.dm
- code/controllers/subsystems/machines.dm
- code/modules/mob/mob_planes_vr.dm
- vorestation.dme
> [CH] GC driving me insane

- maps/southern_cross/southern_cross-1.dmm
- maps/southern_cross/southern_cross-3.dmm
> [CH] (Deck 1/3) Some fixes

- modular_chomp/code/modules/hydro/plants.dm
- modular_chomp/code/modules/reagents/reactions/instant/instant.dm
> [CH] Phoron dragon blood distilling

- modular_chomp/code/modules/event/meatyores.dm
> [CH] Meatyores fix

- code/game/objects/items/mail_ch.dm
> [CH] Mail Tag Fix

- code/_helpers/global_lists_vr.dm
> [CH] VR fixy

- maps/southern_cross/southern_cross-0.dmm
- maps/southern_cross/southern_cross-1.dmm
- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/southern_cross-3.dmm
- maps/southern_cross/southern_cross-5.dmm
- maps/southern_cross/southern_cross-8.dmm
- maps/southern_cross/southern_cross_areas.dm
- modular_chomp/maps/submaps/shelters/TradingShip-40x22.dmm
> [ЗЕРКАЛО] Fixing all the issues I created on the map (Changes Deck 0/1/2/3 as well as Sif Plains and CentCom maps)

- maps/groundbase/gb-z1.dmm
- maps/groundbase/gb-z2.dmm
- maps/groundbase/groundbase_areas.dm
- maps/stellar_delight/stellar_delight1.dmm
- maps/stellar_delight/stellar_delight2.dmm
- maps/stellar_delight/stellar_delight_areas.dm
- maps/tether/tether-01-surface1.dmm
- maps/tether/tether-03-surface3.dmm
- maps/tether/tether_areas.dm
> [VR]  Entrepreneur Expansion Part 2

- code/datums/supplypacks/recreation_vr.dm
> [VR]  Changes pillow crate names on cargo console

- code/modules/lighting/sunlight_handler_ch.dm
> [CH] bandaid for cringe corner deletion

- code/modules/client/preference_setup/vore/07_traits.dm
> [VR]  prevent flags default exclusion

- code/_helpers/global_lists_vr.dm
- maps/southern_cross/submaps/virtual_reality/constructVR.dmm
> [CH] Possible reader fixes?

- code/_onclick/hud/screen_objects.dm
> [CH] Gives a dummy variable a use. hud_enabled

- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/negative.dm
> [CH] One Life trait

- code/__defines/_compile_options.dm
- code/_helpers/game.dm
- code/modules/hydroponics/spreading/spreading.dm
- code/modules/mob/living/carbon/alien/life.dm
- code/modules/mob/living/silicon/robot/life.dm
- modular_chomp/code/game/objects/effects/dark_growth.dm
> [CH] fuck everything (I tried to fix GC stuff again)

- maps/offmap_vr/talon/talon_v2.dmm
> [VR] Fix Talon Vent

- code/modules/lighting/sunlight_handler_ch.dm
> [CH] 8d10 psychic damage (lighting memory optimizations)

- modular_chomp/code/game/objects/items/devices/vacpack.dm
> [CH] Makes vacpack belly nutrition scale with the belly setting

- code/modules/research/prosfab_designs.dm
> [VR] fixes wrong pathing

- code/controllers/configuration_ch/entries/general.dm
- config/example/config.txt
> [CH] Fix config default for radiation to match live

- code/modules/resleeving/autoresleever.dm
> [VR] Reduces vore death timer on autoresleever

- maps/southern_cross/overmap/planets/thor/thor.dmm
- maps/southern_cross/submaps/gateway/darkrps.dm
- maps/southern_cross/submaps/gateway/darkrps.dmm
- modular_chomp/code/modules/mining/shelters_ch.dm
- modular_chomp/maps/overmap/space_pois/space_pois.dm
- modular_chomp/maps/overmap/space_pois/spacebar_40x40.dmm
- modular_chomp/maps/overmap/space_pois/ussp_84x90.dmm
- modular_chomp/maps/submaps/shelters/CultShip-28x17.dmm
- modular_chomp/maps/submaps/shelters/MechFabShip-27x24.dmm
> [CH] Various map fixes

- .github/workflows/ci.yml
> [CH] add 30 minute job timeout to integration tests

- code/modules/mob/living/silicon/robot/robot_vr.dm
> [CH] Fixes borg hand interactions with force-buckled mobs

- code/game/objects/items/falling_object_vr.dm
> [VR] Adds drop vore to mob falling objects

- code/modules/integrated_electronics/subtypes/input.dm
> [CH] Phased Entities Circuitry Fix

- code/modules/admin/admin_verb_lists_vr.dm
- code/modules/eventkit/generic_objects/generic_structure.dm
- vorestation.dme
> [VR] Generic Machines Part 1 - Structure

- code/modules/client/client procs.dm
> [VR] Disable ingame changelog notification

- code/game/objects/structures/loot_piles_ch.dm
> [CH] Makes trashpiles climbable

- maps/southern_cross/submaps/virtual_reality/constructVR.dm
- maps/southern_cross/submaps/virtual_reality/constructVR.dmm
> [CH] minor vr mapping adjustments

- code/modules/overmap/OM_sound.dm
- code/modules/overmap/ships/computers/helm.dm
- maps/southern_cross/southern_cross-7.dmm
> [CH] Fixes OM sounds and allows GPS to track OM planets.

- maps/southern_cross/southern_cross-1.dmm
- maps/southern_cross/southern_cross-2.dmm
> [CH] (Deck 1&2) Mapfixes the escape pods

- code/datums/supplypacks/engineering.dm
> [CH] Freed the rad collector

- code/modules/vore/eating/living_vr.dm
> [VR] AFK vore logging

- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/pda/pda.dm
> [VR] borg typing indicator vanishing and pda hotkey drag for borgs

- code/__defines/belly_modes_vr.dm
- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/bellymodes_vr.dm
> [VR] Belly Mode Addon: Spare Prosthetics

- code/__defines/admin.dm
- code/modules/admin/admin.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/client/verbs/ooc.dm
> [VR] seperate LOOC and OOC mute

- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_rig.dm
> [CH] Makes the protean modsuit control mimic assimilated controls.

- code/modules/vore/eating/living_vr.dm
> [VR] Fix for Digest Pain not loading preference

- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_rig.dm
> [CH] Fixes suit_state of the protean rig when you unassimilate a rig.

- code/modules/clothing/under/miscellaneous_vr.dm
> [CH] Prevent size bracelets resizing above 200

- code/modules/clothing/under/miscellaneous_vr.dm
> Bracelet Sizecap - missed lower end

- tgui/packages/tgui/interfaces/ChemMaster.jsx
> [VR] icon fixes

- code/modules/mob/living/silicon/robot/robot.dm
> [VR] Fixed Typing Indicators getting stuck on borgs

- code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
> [VR] Buff orange/red eye energy gain

- code/ZAS/Fire.dm
- code/ZAS/Turf.dm
- code/__defines/ZAS.dm
- code/__defines/_planes+layers.dm
- code/modules/admin/verbs/mapping.dm
- code/modules/xgm/xgm_gas_data.dm
- code/modules/xgm/xgm_gas_mixture.dm
> [CH] Miscellaneous ZAS Fixes and Optimizations

- modular_chomp/code/modules/mob/living/simple_mob/subtypes/slimess/xenobio.dm
- modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/spacecritters.dm
> [CH] Some Fixes

- code/modules/xgm/xgm_gas_mixture.dm
> [CH] Gas overlays remove when not enough gas

- code/ZAS/Turf.dm
- code/__defines/ZAS.dm
> [CH] ZAS zones separate properly with airlocks

- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral_ch.dm
> [CH] Uncock succubus bite

- code/modules/vore/eating/digest_act_vr.dm
> [CH] Nutrition from absorbed piles now scales with vorgan nutrition percent

- modular_chomp/maps/submaps/shelters/Desert Club-33x33.dmm
> [CH] Desert club sp pod

- code/modules/power/fusion/fuel_assembly/fuel_compressor.dm
> [CH] fix SM duplication exploit

- modular_chomp/maps/overmap/space_pois/dj_31x28.dmm
> [CH] critical mapping error

- modular_chomp/code/modules/weapons/staves.dm
> [CH] Laser Staff Fixed

- code/_onclick/hud/robot.dm
> [VR]  fixes duplicate adding

- code/game/objects/items/weapons/material/ashtray.dm
> [VR]  Reduces ashtray size

- code/modules/assembly/proximity.dm
- code/modules/assembly/timer.dm
- tgui/packages/tgui/interfaces/AssemblyProx.jsx
- tgui/packages/tgui/interfaces/AssemblyTimer.jsx
- tgui/packages/tgui/interfaces/BrigTimer.jsx
> [VR] multiple UI timing issues

- code/game/objects/items/weapons/storage/wallets.dm
> [VR] Fluff Permits in Wallets

- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/submaps/gateway/hiddeneclipse.dmm
- modular_chomp/maps/submaps/surface_submaps/valley/alientomb.dmm
- modular_chomp/maps/submaps/surface_submaps/valley/paperworks.dmm
- modular_chomp/maps/submaps/surface_submaps/valley/piratevox.dmm
- modular_chomp/maps/submaps/surface_submaps/valley/warzone.dmm
> [CH] Some POI Stuff

- code/__defines/gamemode.dm
- code/game/antagonist/station/event.dm
- vorestation.dme
> [VR]  Event character role

- code/modules/mob/living/simple_mob/subtypes/vore/slug_ch.dm
> [CH] Fixes slug glue breaking agresive mobs AI

- code/modules/assembly/proximity.dm
- code/modules/assembly/timer.dm
- tgui/packages/tgui/interfaces/AssemblyProx.jsx
- tgui/packages/tgui/interfaces/AssemblyTimer.jsx
> [VR] works directly with seconds

- code/modules/power/lighting_vr.dm
> [VR] Broken Lights

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/paperwork/silicon_photography.dm
> [VR] change some robotverbs

- code/_onclick/hud/screen_objects.dm
> [CH] fix wrong location

- code/modules/reagents/reagents/medicine_vr.dm
> [VR] Makes Adranol Work

- maps/southern_cross/southern_cross-3.dmm
> [CH] Fixes 2 escape pod accesses in deck 3

- modular_chomp/maps/overmap/space_pois/abandonedzoo_50x50.dmm
- modular_chomp/maps/overmap/space_pois/asteroid4_60x60.dmm
- modular_chomp/maps/overmap/space_pois/space_pois.dm
> [CH] fixes some OM maps not loading, minor map edits

- maps/groundbase/groundbase_defines.dm
- maps/offmap_vr/common_offmaps.dm
- maps/redgate/facility.dmm
- maps/stellar_delight/stellar_delight_defines.dm
- maps/tether/tether_defines.dm
> [VR] Facility Redgate Map

- code/game/area/Space Station 13 areas.dm
- code/modules/virus2/disease2.dm
- maps/southern_cross/southern_cross_areas.dm
- modular_chomp/code/modules/event/infectedroom.dm
- modular_chomp/code/modules/virus2/disease2.dm
> [CH] Infected Room Update

- code/datums/outfits/outfit.dm
- code/game/jobs/job_controller.dm
- code/modules/client/preference_setup/general/04_equipment.dm
- code/modules/client/preferences.dm
> [VR] Ports "No Shoes" from RogueStar

- code/modules/mob/living/carbon/human/species/station/teshari.dm
> [VR] No shoes: Teshari edition

- code/modules/mob/living/silicon/robot/subtypes/gravekeeper.dm
- code/modules/mob/living/silicon/robot/subtypes/lost_drone.dm
- code/modules/vore/eating/bellymodes_vr.dm
- code/modules/vore/eating/living_ch.dm
- modular_chomp/code/modules/mob/living/silicon/robot/dogborg/dog_modules.dm
> [CH] rebalance lost

- code/modules/mob/dead/corpse.dm
- code/modules/mob/dead/corpse_ch.dm
> [CH] remove partially duplicated code

- code/modules/vore/eating/belly_obj_vr.dm
> [CH] add auto transfer messages to auto autotransfer

- code/modules/reagents/reagents/medicine_vr.dm
> [CH] tf pref for chem

- code/modules/power/cell.dm
> [CH] undo some initialize changes

- code/game/turfs/turf.dm
- code/modules/mob/living/living_defense.dm
> [VR] Changes wall damage from being (usually) 25 brute to 12 and doesnt add a stun to it

- code/modules/client/preference_setup/loadout/loadout_accessories_vr.dm
- code/modules/clothing/under/accessories/torch.dm
> [VR] Uniform Insignia

- code/controllers/subsystems/media_tracks.dm
- code/game/machinery/jukebox.dm
- code/modules/vore/eating/vorepanel_vr.dm
- tgui/packages/tgui/interfaces/Jukebox.jsx
> [VR] admin jukeboxsong handling

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/living.dm
> [VR] Toggle Sleep

- code/modules/clothing/masks/miscellaneous_vr.dm
> mirror fail

- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/exportpanel_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
- tgui/packages/tgui/interfaces/VorePanel.jsx
- tgui/packages/tgui/interfaces/VorePanelExport.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyDescriptions.tsx
> [VR] allow to only show suitable belly messages

- code/modules/mob/living/silicon/robot/inventory.dm
> [VR] small workaround for borg GPS

- code/modules/client/preference_setup/global/setting_datums.dm
- code/modules/client/preferences_vr.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/living.dm
- code/modules/mob/mob_defines.dm
> [VR] Auto-AFK

- code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
> [CH] Shadekin Dark Respite now fixes severe infections.

- maps/virgo_minitest/virgo_minitest-1.dmm
> [VR] Testmap Mini Chemlab

- code/game/jobs/job/captain_vr.dm
- code/game/jobs/job/civilian_vr.dm
- code/game/jobs/job/engineering_vr.dm
- code/game/jobs/job/exploration_vr.dm
- code/game/jobs/job/medical_vr.dm
- code/game/jobs/job/science_vr.dm
- code/game/jobs/job/security_vr.dm
> [VR] Adds new fax reason for expedition teams

- code/controllers/subsystems/statpanel_ch.dm
> [CH] re add station date to the panel

- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
> [CH] hide some verbs

- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyDescriptions.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport.tsx
> [CH] Transfer Message Changes

- code/modules/projectiles/guns/energy.dm
> [CH] another case of update_icon in NEW

- code/game/objects/effects/decals/Cleanable/humans.dm
- code/game/objects/effects/decals/Cleanable/tracks.dm
- code/game/objects/effects/decals/cleanable.dm
> [VR] fix jan HUD visibility

- code/_helpers/text.dm
- tgui/packages/tgui-panel/audio/NowPlayingWidget.jsx
- tgui/packages/tgui-panel/chat/renderer.jsx
- tgui/packages/tgui/interfaces/VorePanel.jsx
> [VR] allows to use more newline breaks for longer posts

- code/modules/tgui_panel/tgui_panel.dm
> [VR] tg chat loading improvement

- code/modules/persistence/effects/paper.dm
> [VR] Persistent papers should not replace the chat window

- code/game/objects/effects/decals/cleanable.dm
- code/modules/admin/verbs/modify_robot.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/vore/eating/digest_act_vr.dm
- code/modules/xenobio2/mob/xeno.dm
> [VR] some GC things

- code/modules/vore/eating/living_ch.dm
> [CH] belly liquid examine percentage

- maps/southern_cross/submaps/gateway/snowfield.dmm
> [CH] Armory Doors are wierd

- code/datums/components/resize_guard.dm
> [VR] >200% size exploit

- tgui/yarn.lock
> [CH] Bump braces from 3.0.2 to 3.0.3 in /tgui

- code/modules/vore/persist/persist_vr.dm
> [VR] small runtime fix for #16036

- code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
> [CH] Fixes vore sprites breaking for non-humanoid shaped xenochimera

- modular_chomp/code/game/objects/items/weapons/storage/firstaid.dm
- modular_chomp/code/modules/client/preference_setup/loadout/loadout_general.dm
> [CH] Adds medications as loadout items

- code/modules/mob/living/carbon/human/death.dm
- code/modules/organs/organ_external.dm
> [CH] Reduces bloodloss from getting burns

- modular_chomp/code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
> [CH] implant drop

- modular_chomp/code/game/machinery/vending.dm
> [CH] Nifs are now logged, and sec accessible

- code/datums/datacore.dm
- code/game/jobs/job/job.dm
- code/game/jobs/job_controller.dm
- modular_chomp/code/game/jobs/job/noncrew.dm
> [CH] linear anomaly limit

- maps/southern_cross/southern_cross-6.dmm
- modular_chomp/code/game/machinery/paradox.dm
> [CH] Paradox Gen Friendliness Update

- code/modules/organs/internal/eyes.dm
> [CH] Fixes synth eye color verb

- code/game/atoms.dm
> [CH] fixes phantom blood stains

- code/modules/instruments/songs/editor.dm
> [VR] some less rounding

- code/modules/nifsoft/nif.dm
> [VR] small nif fix

- code/modules/examine/descriptions/armor.dm
> [VR] Exact Temp & Pressure on Armour Examine

- code/modules/tgui_panel/tgui_panel.dm
- tgui/packages/tgui-panel/telemetry.js
> [VR] do an actual timeout test for chat inits

- maps/southern_cross/southern_cross-8.dmm
> [CH] Vend-B-Gone

- tgui/yarn.lock
> [CH] Bump ws from 7.5.9 to 8.17.1 in /tgui

- .gitignore
- Dockerfile
- code/modules/asset_cache/asset_list.dm
> [CH] move asset cache dir

- tools/pull_request_hooks/changelogConfig.js
- tools/pull_request_hooks/changelogParser.js
> [CH] default unknown keys to rscadd

- code/modules/vore/resizing/sizegun_vr.dm
> [VR] Unstable Size Gun

- code/modules/food/food/drinks/bottle.dm
> [VR] Spin The Bottle

- code/modules/media/mediamanager.dm
> [VR] We should return if it's qdeleted, not if it's not qdeleted

- tgui/packages/tgui-panel/chat/middleware.js
- tgui/packages/tgui-panel/settings/reducer.js
> [VR] fix chat deadlock on first init

- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
> [CH] Flexible Digestion Damage

- code/__defines/is_helpers.dm
- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/mob/living/silicon/robot/analyzer.dm
- code/modules/mob/living/silicon/robot/robot.dm
> [VR] Disables shell renaming

- code/modules/food/food/drinks.dm
- code/modules/mob/living/carbon/human/species/species.dm
- code/modules/mob/living/carbon/human/species/station/prometheans.dm
- code/modules/mob/living/carbon/human/species/station/station.dm
- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
- code/modules/reagents/reagents/dispenser.dm
> [VR] Alcohol Trait Refactor

- code/modules/reagents/reagent_containers/patch.dm
> [VR] Make Patches Useful(?)

- code/modules/clothing/gloves/miscellaneous.dm
> [VR] Survival Watch Light Level

- code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
- code/modules/reagents/reagents/vore_vr.dm
- code/modules/vore/eating/living_vr.dm
> [VR] Ports Venom Bite / Injection from Rogue Star

- modular_chomp/code/modules/mob/living/carbon/human/species/station/station_ch.dm
> [CH] Makes plonts lizard speed

- modular_chomp/code/modules/overmap/dynamic_sector.dm
> [CH] Drop dynamic z levels for OM from 3 to 2

- modular_chomp/code/modules/planet/sif.dm
> [CH] Anomalous Weather Update Part 1.5

- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/positive.dm
> [CH] Frees Weaver

- 1SP_pods.dmm
- modular_chomp/code/modules/mining/shelter_atoms_ch.dm
- modular_chomp/code/modules/mining/shelters_ch.dm
- modular_chomp/maps/submaps/shelters/DragonCave-18x18.dmm
> [CH] Adds a new outsider pod option, the dragon cave!

- code/modules/mob/new_player/new_player.dm
> [CH] Re-enables polling

- code/game/turfs/simulated/outdoors/grass_ch.dm
- modular_chomp/code/datums/crafting/recipes.dm
- modular_chomp/code/game/objects/structures/flora.dm
- vorestation.dme
> [CH] Outsider Buff - Fiber Addition

- code/modules/mob/new_player/new_player.dm
> [CH] Increase main menu window height to kill the scrollbar

- modular_chomp/code/datums/elements/slosh.dm
> [CH] Fixes random slosh sounds happening rarely

- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
> [CH] Fixes venom injection

- tgui/packages/tgui/interfaces/EmbeddedController/index.tsx
> [VR] removes a debug

- modular_chomp/code/modules/mining/shelter_atoms_ch.dm
- modular_chomp/code/modules/mining/shelters_ch.dm
- modular_chomp/maps/submaps/shelters/ExplorerHome-17x20.dmm
- modular_chomp/maps/submaps/shelters/Hotel-36x18.dmm
- modular_chomp/maps/submaps/shelters/Logcabin-19x9.dmm
- modular_chomp/maps/submaps/shelters/LoneHomeclean-18x22.dmm
- modular_chomp/maps/submaps/shelters/NewHotel-18x22.dmm
- modular_chomp/maps/submaps/shelters/SurvivalDIYlite-11x11.dmm
- modular_chomp/maps/submaps/shelters/XenobotanySetup-19x11.dmm
> [CH] 5 new superposed pods

- maps/redgate/fantasy_dungeon.dmm
- maps/redgate/jungle.dmm
> [VR] Replaces demons in fantasy dungeon

- maps/southern_cross/submaps/gateway/diescraper.dm
- maps/southern_cross/submaps/gateway/diescraper.dmm
> [CH] Diescraper Fixes

- code/modules/resleeving/autoresleever.dm
- code/modules/resleeving/machines.dm
- code/modules/vore/eating/inbelly_spawn.dm
- modular_chomp/code/datums/elements/footstep.dm
> [CH] Reduces the footstep volume, and some fixes

- tgui/packages/tgui/interfaces/Cryo/CryoContent.tsx
- tgui/packages/tgui/interfaces/Cryo/constants.ts
> [VR] fix: cryo UI fixes

- modular_chomp/code/game/jobs/job/noncrew.dm
> [CH] Change base Shadekin spawns from 3 to 5

- modular_chomp/code/datums/elements/slosh.dm
> [CH] Slosh fixes

- maps/stellar_delight/stellar_delight1.dmm
> [VR] SD Maint Door Fix 2

- tgui/packages/tgui/interfaces/CloningConsole/types.ts
- tgui/packages/tgui/interfaces/ResearchConsole/index.tsx
> [VR] fixes RD console

- code/game/objects/structures/morgue.dm
> [VR] Crematoriums shouldn't break when they fail to open.

- tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
- tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
- tgui/packages/tgui-panel/styles/tgchat/chat-vchatdark.scss
- tgui/packages/tgui-panel/styles/tgchat/chat-vchatlight.scss
> [VR] resyncs chat styles

- code/datums/observation/turf_enterexit.dm
- code/game/atoms.dm
- code/game/machinery/camera/camera.dm
- code/game/machinery/camera/motion.dm
- code/game/machinery/camera/presets.dm
- code/game/machinery/flasher.dm
- code/game/objects/items/devices/transfer_valve.dm
- code/game/objects/items/weapons/tanks/tanks.dm
- code/modules/assembly/holder.dm
- code/modules/assembly/proximity.dm
- code/modules/hydroponics/spreading/spreading.dm
- code/modules/hydroponics/spreading/spreading_response.dm
- code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
- code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
- code/modules/power/singularity/containment_field.dm
> [CH] Memory leak fix

- modular_chomp/code/modules/mob/living/living.dm
> [CH] Footstep runtime fix

- code/modules/assembly/signaler.dm
- code/modules/mob/living/living_defense.dm
> [CH] Re-adds stealth removed signaler deadman switch.

- code/__defines/_planes+layers_vr.dm
> [VR] tummy hotfix

- code/controllers/configuration_ch.dm
- code/controllers/configuration_ch/entries/chompstation.dm
- code/controllers/subsystems/job.dm
- code/game/jobs/job/job.dm
- code/game/jobs/job_controller.dm
- code/game/machinery/computer/timeclock_vr.dm
- code/modules/mob/new_player/new_player_vr.dm
- modular_chomp/code/game/jobs/job/noncrew.dm
> [CH] [READY TO MERGE] Port's RS's anti job camping to Anomoly

- code/controllers/subsystems/mail_ch.dm
- code/game/objects/items/mail_ch.dm
- code/modules/admin/admin_verb_lists_vr.dm
- maps/southern_cross/southern_cross-1.dmm
- maps/southern_cross/southern_cross-2.dmm
- modular_chomp/code/datums/supplypacks/supply.dm
- vorestation.dme
> [CH] Blank Mail Envelopes

- code/modules/organs/organ_external.dm
> [CH] Makes bone breaks in bellies only audible in whisper range

- ATTRIBUTIONS.md
> [VR] ATTRIBUTIONS.md Update

- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyInteractions.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/types.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportBellyString.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportBellyStringHelpers.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/constants.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/types.ts
> [CH] Extra Auto-Transfer Locations

- modular_chomp/code/modules/clothing/spacesuits/rig/suits/alien.dm
> [CH] Vox Eng suit pressure fix test

- code/modules/artifice/telecube.dm
> [CH] Changes loci to address some issues

- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/southern_cross-3.dmm
> [CH] Removes round start sci PA, Moves ore storage to cargo warehouse.

- modular_chomp/code/modules/mining/shelters_ch.dm
- modular_chomp/maps/submaps/shelters/MechFabShip-27x24.dmm
- modular_chomp/maps/submaps/shelters/MechStorageFab-32x24.dmm
- modular_chomp/maps/submaps/surface_submaps/plains/oldhotel.dmm
> [CH] Outsider pod nerfs

- maps/southern_cross/southern_cross-2.dmm
> [CH] Makes the sci break room a little better

- code/modules/vore/eating/inbelly_spawn.dm
- vorestation.dme
> [CH] Re-enables spawn in belly verb for ghosts

- code/modules/vore/eating/living_vr.dm
> [VR] OOC Escape Food

- code/modules/fishing/fishing_net.dm
> [VR] Butterfly net description

- code/modules/mob/new_player/new_player.dm
> [VR] Extend Welcome Window

- code/modules/clothing/spacesuits/void/station.dm
- code/modules/clothing/spacesuits/void/station_vr.dm
> [VR] Helmet Cams on Networks

- code/modules/mob/new_player/new_player_vr.dm
> [CH] fix ano message

- modular_chomp/code/modules/vore/eating/soulcatcher.dm
- modular_chomp/code/modules/vore/eating/soulcatcher_mob.dm
> [CH] Soul catcher sanity

- code/modules/client/preference_setup/loadout/loadout.dm
- code/modules/client/preference_setup/loadout/loadout_accessories.dm
- code/modules/client/preference_setup/loadout/loadout_accessories_vr.dm
- code/modules/client/preference_setup/loadout/loadout_accessories_yw.dm
- code/modules/client/preference_setup/loadout/loadout_eyes.dm
- code/modules/client/preference_setup/loadout/loadout_eyes_vr.dm
- code/modules/client/preference_setup/loadout/loadout_eyes_yw.dm
- code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
- code/modules/client/preference_setup/loadout/loadout_gloves.dm
- code/modules/client/preference_setup/loadout/loadout_suit.dm
- code/modules/client/preference_setup/loadout/loadout_suit_vr.dm
- code/modules/client/preference_setup/loadout/loadout_suit_yw.dm
- code/modules/client/preference_setup/loadout/loadout_uni_selector.dm
- code/modules/client/preference_setup/loadout/loadout_xeno.dm
- modular_chomp/code/modules/client/preference_setup/loadout/loadout_suit.dm
> [VR] Loadout Restrictions Specified

- code/modules/mob/living/carbon/human/stripping.dm
- tgui/packages/tgui/interfaces/InventoryPanelHuman.tsx
> [VR] Stripping Underclothing

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/species_vr.dm
- code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
- code/modules/mob/living/carbon/human/species/station/teshari_vr.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/species.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/station.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/teshari.dm
> [VR] Fixes teshari stomachs & Unathi Stomachs

- modular_chomp/code/datums/crafting/recipes.dm
> [CH] Fixes infinite sandstone/marble things, I think

- code/modules/client/preference_setup/loadout/loadout_suit.dm
- code/modules/clothing/suits/miscellaneous.dm
> [VR] Patchless Military Jackets

- code/modules/research/circuitprinter.dm
- code/modules/research/protolathe.dm
- code/modules/research/rdconsole.dm
- code/modules/research/rdconsole_tgui.dm
- modular_chomp/code/modules/research/rdconsole.dm
> [CH] Removes some designs from the public circuit printer

- maps/southern_cross/southern_cross-2.dmm
> [CH] makes cargo storage require cargo access and makes external walls r_walls

- modular_chomp/code/datums/crafting/recipes.dm
> [CH] Fixes two other crafts

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- interface/skin.dmf
- modular_chomp/code/modules/mob/living/carbon/human/human.dm
- modular_chomp/code/modules/mob/living/carbon/human/human_defines.dm
> [VR] Choose to rest left or right

- code/modules/reagents/reagent_containers/syringes.dm
> [CH] Allows reagents to be injected into chewables

- code/__defines/mobs.dm
- code/modules/mob/_modifiers/modifiers_vr.dm
> [CH] Adjusts diver visibility in shallow water

- code/game/objects/items/devices/lightreplacer.dm
> [VR] allows cyborg glass recyclers to refill lightreplacers

- code/modules/mob/living/bot/bot.dm
- code/modules/vore/eating/living_vr.dm
> [VR] edits some no_vore usage

- code/modules/vore/resizing/crackers.dm
> [VR] Fix for bluespace crackers

- code/__defines/footsteps_ch.dm
- code/_helpers/global_lists_ch.dm
- code/modules/client/preference_setup/vore/02_size.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/simple_mob/simple_mob.dm
- code/modules/mob/living/simple_mob/simple_mob_vr.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/resleeving/autoresleever.dm
- code/modules/resleeving/machines.dm
- code/modules/vore/eating/inbelly_spawn.dm
- code/modules/vore/eating/living_vr.dm
- modular_chomp/code/datums/elements/footstep.dm
- modular_chomp/code/datums/elements/slosh.dm
- russian/_lib/_lists_ru.dm
> [CH] Custom Footstep sounds

- code/__defines/admin_ch.dm
- code/modules/admin/verbs/smite.dm
> [CH] Adds a new smite

- modular_chomp/code/datums/elements/footstep.dm
> [CH] Step Element runtime fix

- code/modules/xenoarcheaology/effect_master.dm
- code/modules/xenoarcheaology/finds/find_spawning.dm
> [VR] Xenoarch effects were editing the reference list

- tgui/packages/tgui/components/Modal.tsx
- tgui/packages/tgui/interfaces/NumberInputModal.tsx
- tgui/packages/tgui/interfaces/TextInputModal.tsx
- tgui/packages/tgui/interfaces/common/ComplexModal.tsx
- tgui/packages/tgui/layouts/Window.tsx
> [VR] input ids & game focus loss fix

- code/game/jobs/job_controller.dm
> [CH] Vorespawn Pref Tweaks

- modular_chomp/code/modules/mob/living/silicon/robot/sprites/mining.dm
> [CH] dullahan cargo/miner fix

- modular_chomp/code/modules/vore/eating/soulcatcher.dm
> [CH] seperate SC toggling and signal proc to prevent message spam

- code/game/objects/structures/signs.dm
- maps/tether/tether-01-surface1.dmm
- maps/tether/tether-03-surface3.dmm
> [VR] Signs and Safety

- code/game/machinery/airconditioner_vr.dm
> [VR] fix thermal regulators not allowing negative temperatures

- code/modules/virus2/diseasesplicer.dm
- tgui/packages/tgui/interfaces/DiseaseSplicer.tsx
> [VR] fix splicer

- code/modules/client/client procs.dm
> [VR] Add a verb to turn on and off the verb panel

- code/__defines/belly_modes_ch.dm
- code/game/jobs/job_controller.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/vore/eating/belly_obj_ch.dm
- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyOptions.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/constants.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanel/types.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportBellyString.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/types.ts
> [CH] Vorespawn Whitelist and Absorb

- code/modules/overmap/ships/ship.dm
- maps/offmap_vr/om_ships/geckos.dm
- maps/offmap_vr/om_ships/mackerels.dm
- maps/offmap_vr/om_ships/mercship.dm
- maps/offmap_vr/om_ships/salamander.dm
- maps/offmap_vr/om_ships/sdf_corvettes.dm
> [VR] Ship Transponder Flip

- code/modules/paperwork/faxmachine.dm
> [CH] show the borgs name, not 1 when authenticated

- modular_chomp/code/modules/point/point.dm
> [CH] Fixes pointing not facing the atom pointed

- modular_chomp/code/modules/vore/eating/soulcatcher.dm
> [CH] fix transfer self

- code/game/objects/items/mail_ch.dm
> [CH] Mail bag fix + bigger capacity

- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
> [CH] Fixes bigdragon scaling issues.

- code/modules/mob/hear_say.dm
> [VR] fix holospeak

- code/modules/reagents/reagent_containers/borghypo.dm
- code/modules/surgery/limb_reattach.dm
- code/modules/surgery/organs_internal.dm
- code/modules/surgery/robotics.dm
> [CH] Fixes various runtimes regarding balloon alerts

- code/modules/research/rdconsole.dm
> [VR] disconnect devices on RD console dismantle

- code/modules/materials/materials/metals/steel.dm
- code/modules/materials/materials/organic/wood.dm
> [VR] Craftable Shelves

- code/modules/economy/vending_machines.dm
> [VR] add armbands to engineering vendors

- code/modules/client/preference_setup/global/01_ui.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_toggle_procs.dm
- code/modules/mob/mob.dm
> [VR] Revert Throw Notifs

- maps/om_adventure/grasscave.dm
- maps/om_adventure/grasscave.dmm
> [VR] Spacewhale LZs

- code/modules/vore/chat_healthbars.dm
> [VR] healthbars now respect selective mode

- code/modules/events/electrical_storm.dm
> [VR] Update electrical_storm.dm

- code/modules/client/preference_setup/loadout/loadout_suit_vr.dm
- code/modules/clothing/suits/armor_vr.dm
- code/modules/mining/abandonedcrates_vr.dm
> [VR] Martian miner coat adjustments

- code/__defines/is_helpers.dm
- code/game/objects/items/devices/e_beacon.dm
- code/game/objects/structures/crates_lockers/closets/misc_vr.dm
> [VR] Emergency Beacon Update

- code/datums/supplypacks/supply.dm
> [VR] Away Team/Pilot Supply Crates

- code/modules/mob/living/simple_mob/simple_mob_vr.dm
- code/modules/mob/living/simple_mob/subtypes/vore/succubi.dm
- code/modules/vore/eating/belly_obj_vr.dm
> [VR] Adds auto-transfer on absorb function, selective mode chance function, and applies both to succubi

- modular_chomp/code/modules/vore/eating/soulcatcher.dm
> [CH] Makes sure that souls caught in the vore soulcatcher actually have their prefs

- code/modules/client/preferences.dm
- code/modules/client/preferences_ch.dm
- code/modules/mob/new_player/preferences_setup.dm
> [VR] Fix Charsetup Tail Layering

- code/modules/reagents/machinery/dispenser/dispenser2.dm
- tgui/packages/tgui/interfaces/ChemDispenser/ChemDispenserBeaker.tsx
- tgui/packages/tgui/interfaces/ChemDispenser/ChemDispenserChemicals.tsx
- tgui/packages/tgui/interfaces/ChemDispenser/ChemDispenserRecipes.tsx
- tgui/packages/tgui/interfaces/ChemDispenser/ChemDispenserSettings.tsx
- tgui/packages/tgui/interfaces/ChemDispenser/index.tsx
- tgui/packages/tgui/interfaces/ChemDispenser/types.ts
> [VR] Add recipe macro recording to reagent dispenser

- code/modules/client/preference_setup/general/03_body.dm
- code/modules/client/preference_setup/vore/07_traits.dm
> [VR] Fixes species blood color

- code/modules/vore/eating/living_vr.dm
> [CH] only add the object for the soulcatcher when we also reload/add bellies

- code/modules/mob/living/voice/voice.dm
> [CH] Allows mind-binded creatures to use any emote (FIXED!!)

- modular_chomp/code/modules/projectiles/guns/energy.dm
- vorestation.dme
> [CH] combat update hotfix

- modular_chomp/code/modules/projectiles/guns/bullet.dm
> [CH] Fixes some bullets doing improper damage.

- code/game/objects/items/weapons/material/twohanded_vr.dm
- code/modules/power/port_gen.dm
- code/modules/power/port_gen_vr.dm
> [VR] some RS ports

- code/game/atoms.dm
- code/game/objects/items/devices/transfer_valve.dm
- code/game/objects/items/weapons/tanks/tanks.dm
> [CH] Fixes various HasProximity runtimes

- code/modules/power/batteryrack.dm
- tgui/packages/tgui/interfaces/Batteryrack.tsx
> [VR] adds cell names to the battery rack

- code/modules/mob/living/simple_mob/subtypes/vore/goia_ch.dm
> [CH] fixes goia grabs

- vorestation.dme
> [CH] updating DME to allow syndie dullahans show in selection menu (bugfix))

- code/game/objects/items/toys/toys_vr.dm
> [VR] Fix for bait toy

- code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
- code/modules/projectiles/guns/energy/phase.dm
- code/modules/projectiles/guns/projectile/zz_ballistics_ch.dm
- modular_chomp/code/modules/projectiles/ammo_refactor/ammo_overrides.dm
- modular_chomp/code/modules/projectiles/guns/bullet.dm
- modular_chomp/code/modules/projectiles/guns/energy/laser.dm
- vorestation.dme
> [CH] Fixes a handful of weapons shooting the wrong projectile, phase weapon nerf, floragun buff, one merc nerf.

- tgui/packages/tgui-dev-server/package.json
- tgui/yarn.lock
> [CH] Bump axios from 1.6.8 to 1.7.4 in /tgui

- code/modules/tooltip/tooltip.dm
- code/modules/tooltip/tooltip.html
> [VR] Fix tooltips not working on mobs

- code/game/objects/random/misc.dm
- code/game/objects/random/mob_vr.dm
- code/modules/economy/vending_machines_vr.dm
- maps/expedition_vr/aerostat/aerostat_science_outpost.dmm
- maps/offmap_vr/talon/talon_v2.dm
- maps/redgate/cybercity.dmm
- maps/redgate/facility.dmm
- maps/redgate/jungle_underground.dmm
- maps/redgate/train_upper.dmm
- maps/stellar_delight/stellar_delight3.dmm
> [VR] Adjusts stationside first aid spawns

- modular_chomp/code/game/objects/items/devices/vacpack.dm
> [CH] limit vacuum size

- code/game/mecha/components/armor.dm
- code/game/mecha/mecha.dm
> [CH] Nerfs mech armor

- code/modules/vore/eating/belly_obj_vr.dm
> [VR] Fixed vore struggle animation not working

- code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
> [VR] Fluff Item Whitelist Addition

- code/modules/reagents/machinery/dispenser/dispenser2.dm
- tgui/packages/tgui/interfaces/ChemDispenser/ChemDispenserRecipes.tsx
- tgui/packages/tgui/interfaces/Sleeper/index.tsx
- tgui/packages/tgui/interfaces/SupplyConsole/SupplyConsoleMenu.tsx
> [VR] allows to delete singular recipes from the ChemDispenser & Makes sleeper+supply scrollable

- tgui/packages/tgui/interfaces/SupplyConsole/SupplyConsoleMenu.tsx
- tgui/packages/tgui/interfaces/SupplyConsole/SupplyConsoleMenuHistoryExport.tsx
- tgui/packages/tgui/interfaces/SupplyConsole/SupplyConsoleMenuOrderList.tsx
> [VR] fix supply console scrolling not working

- code/modules/economy/vending_machines.dm
> [CH] Adds teppi plushies to the vending machine

- code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
> [VR] Venomous Bite Injection Rounding Error Fix

- code/modules/mob/living/carbon/human/human_attackhand.dm
- tgui/packages/tgui/components/DraggableControl.jsx
- tgui/packages/tgui/components/NumberInput.tsx
> [VR] refocusses number input on clicks

- tgui/yarn.lock
> [CH] Bump micromatch from 4.0.5 to 4.0.8 in /tgui

- code/game/objects/items/weapons/circuitboards/machinery/research.dm
- code/modules/research/designs/circuits/circuits.dm
- maps/southern_cross/southern_cross-2.dmm
- modular_chomp/code/modules/research/lathes/protolathe.dm
> [CH] Fixes departmental lathes changing to omni lathes

- code/modules/research/rdconsole.dm
- maps/southern_cross/southern_cross-2.dmm
> [CH] Protolathes Fix: Round 2

- code/modules/research/server.dm
> [CH] Allows lathes to sync to the core sever

- code/controllers/subsystems/nightshift.dm
- maps/~map_system/maps.dm
> [CH] Night shift preparations

- code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
- code/modules/mob/living/living_movement.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/species.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/negative.dm
> [CH] Lesser Lightweight

- code/modules/mining/ore_redemption_machine/survey_vendor.dm
- modular_chomp/code/modules/projectiles/guns/pump.dm
- vorestation.dme
> [CH] Frontier Shotgun

- modular_chomp/code/modules/projectiles/guns/pump.dm
> [CH] FS Fixes

- code/modules/research/server.dm
> [CH] Add sec ID to server

- code/modules/admin/verbs/adminhelp.dm
- code/modules/client/verbs/ooc.dm
- code/modules/mob/mob.dm
> [VR]  Required admin privileges restrictions

- code/modules/research/designs/circuits/circuits.dm
> [CH] unique bord ids

- code/game/objects/items/weapons/chewables.dm
> [CH] Allows to stick micros to lollipops

- code/modules/mob/living/login.dm
- modular_chomp/code/modules/vore/eating/soulcatcher.dm
- modular_chomp/code/modules/vore/eating/soulcatcher_mob.dm
> [CH] SC transfer verb

- modular_chomp/code/modules/mob/living/silicon/robot/sprites/exploration.dm
- modular_chomp/code/modules/mob/living/silicon/robot/sprites/janitor.dm
- modular_chomp/code/modules/mob/living/silicon/robot/sprites/medical.dm
> [CH] move to unique paths

- maps/expedition_vr/space/fueldepot.dmm
> [VR]  Fuel Depot Update

- code/modules/mob/living/simple_mob/subtypes/vore/morph/morph.dm
> [VR]  fix morph takeover

- code/modules/client/preferences.dm
> [VR]  properly copy characters after confirmation or fully abandon it

- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon_ch.dm
- code/modules/mob/living/simple_mob/subtypes/vore/goia_ch.dm
> [VR]  fix icons and layer of bigdragon on revive

- code/modules/organs/robolimbs.dm
> [VR]  Adds Robotic Digitigrade Legs

- code/modules/vore/eating/vorepanel_vr.dm
- tgui/packages/tgui/interfaces/VorePanel/VoreBellySelectionAndCustomization.tsx
- tgui/packages/tgui/interfaces/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyDescriptions.tsx
- tgui/packages/tgui/interfaces/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyVisuals.tsx
- tgui/packages/tgui/interfaces/VorePanel/constants.ts
- tgui/packages/tgui/interfaces/VorePanel/index.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/FeatureColorInput.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyDescriptions.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyVisuals.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/constants.ts
> [VR]  Vore Panel tweaks and fixes

- code/modules/mob/new_player/new_player.dm
> [CH] select belly after reload on predspawn

- code/_onclick/hud/robot.dm
> [VR]  vtec module fix

- code/game/objects/effects/landmarks.dm
- maps/southern_cross/overmap/space/fueldepot.dm
- maps/southern_cross/overmap/space/fueldepot.dmm
- maps/southern_cross/southern_cross_defines.dm
- modular_chomp/code/global.dm
- modular_chomp/code/modules/client/preferences_spawnpoints.dm
- modular_chomp/maps/overmap/om_ships/cybershuttle-10x11.dmm
- modular_chomp/maps/overmap/om_ships/metawhiteship.dm
- modular_chomp/maps/overmap/om_ships/metawhiteship30x21.dmm
- modular_chomp/maps/overmap/om_ships/offmap.dm
- modular_chomp/maps/overmap/om_ships/pizzashuttle.dm
- modular_chomp/maps/overmap/om_ships/sdf_corvettes.dm
- modular_chomp/maps/overmap/om_ships/whiteship-26x33.dmm
> [CH] Adds a new spawnpoint to spacefarers, the fuel depot.

- code/modules/persistence/storage/smartfridge.dm
> [CH] Persistant Storage Alterations

- code/__defines/admin_vr.dm
- code/modules/admin/verbs/smite.dm
> [VR] Spice Smites

- code/modules/client/preference_setup/vore/07_traits.dm
- code/modules/mob/new_player/new_player_vr.dm
> [VR]  Revert "Revert "Removed negative trait limit""

- code/datums/supplypacks/contraband.dm
- code/game/objects/items/devices/hacktool.dm
> [VR]  Mini Hacktool Expansion

- code/modules/mob/living/carbon/human/species/lleill/lleill.dm
> [CH] Illell Adjustment

- code/game/gamemodes/events/wormholes.dm
- code/game/objects/effects/portals.dm
- modular_chomp/code/modules/event/event_container_ch.dm
- vorestation.dme
> [CH] Re-Enables wormholes event

- code/modules/vore/eating/vorepanel_vr.dm
> [VR]  belly input failure message on close

- code/modules/samples/samples.dm
> [VR]  Sample Handling Tweaks

- code/modules/vore/eating/living_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- tgui/packages/tgui/interfaces/VorePanel/VoreUserPreferences.tsx.tsx
> [VR]  Load Prefs From Slot

- code/modules/vore/eating/living_vr.dm
> [CH] examine belly rub target desc

- code/modules/admin/verbs/adminpm.dm
> [VR]  AdminPM rights

- code/modules/mob/living/carbon/human/human_helpers.dm
> [VR] fix belly sprite vis toggling

- code/modules/vore/eating/belly_obj_vr.dm
> [VR]  preemptively remove empty strings from bad formatting

- maps/redgate/facility.dmm
> [VR]  Facility map fix

- tgui/packages/tgui-panel/chat/model.js
- tgui/packages/tgui/components/Input.tsx
> [VR]  textbox not respecting value changes

- code/game/machinery/computer/station_alert.dm
> [VR]  fix alarm proc calls

- maps/southern_cross/overmap/space/fueldepot.dmm
- modular_chomp/code/modules/mining/shelter_atoms_ch.dm
- modular_chomp/maps/overmap/om_ships/cybershuttle-10x11.dmm
- modular_chomp/maps/overmap/om_ships/cybershuttle.dm
- modular_chomp/maps/overmap/om_ships/metawhiteship.dm
- modular_chomp/maps/overmap/om_ships/metawhiteship30x21.dmm
- modular_chomp/maps/overmap/om_ships/pizzashuttle-11x13.dmm
- modular_chomp/maps/overmap/om_ships/pizzashuttle.dm
- modular_chomp/maps/overmap/om_ships/whiteship-26x33.dmm
- modular_chomp/maps/overmap/om_ships/whiteship.dm
> [CH] Spacefarer patches

- code/datums/colormate.dm
- code/game/machinery/painter_vr.dm
- tgui/packages/tgui/interfaces/ColorMate/ColorMateMatrix.tsx
> [VR]  Adds config Input to the colorMatrix

- code/modules/paperwork/faxmachine.dm
- modular_chomp/maps/overmap/om_ships/whiteship-26x33.dmm
> [CH] Makes fax machines init instead of new() 

- code/modules/mob/living/simple_mob/life.dm
> [VR] add sleep handling to simple_mobs

- code/modules/vore/eating/living_vr.dm
> [VR] adds a belly when there is none

- code/modules/food/food/lunch.dm
> [VR] Mega Nukies Disallowed From Vacuum Flask

- code/modules/mob/mob.dm
- interface/skin.dmf
> [VR] Add spacebar throwing to hotkey mode

- code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
> [VR] Allows hanner to take some positive traits at cost

- code/game/objects/items/weapons/id cards/cards.dm
- code/modules/mining/machinery/machine_processing.dm
- code/modules/mining/ore_redemption_machine/equipment_vendor.dm
- code/modules/mob/living/silicon/robot/robot_modules/station.dm
> [VR] Robot Mining ID

- modular_chomp/code/game/objects/items/weapons/id_cards.dm
- modular_chomp/code/modules/mob/living/silicon/robot/modules/exploration.dm
- vorestation.dme
> explo borg card

- code/_helpers/global_lists.dm
> [VR] tesh aren't whitelisted

- code/__defines/chat.dm
- code/modules/examine/examine.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/silicon/ai/examine.dm
- code/modules/mob/living/silicon/pai/examine.dm
- code/modules/mob/living/silicon/robot/examine.dm
> [VR] Add examine_block to mob examine

- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/positive.dm
> [CH] Weaver protean

- code/modules/mob/mob.dm
- interface/skin.dmf
> [CH] Reverts the spacebar toggling R key

- tools/ci/compile_and_run.sh
> [VR]  Make tests actually run on all maps when SD is selected

- maps/tether/tether_things.dm
> [VR]  Remove unused console

- code/game/machinery/computer/station_alert.dm
> [VR]  move alert icon call to it's own proc

- maps/southern_cross/southern_cross-0.dmm
> [CH] Deck 0 fixes

- code/modules/mob/living/voice/voice.dm
- modular_chomp/code/modules/tickets/tickets.dm
> [CH] some small things

- code/modules/vore/eating/belly_obj_vr.dm
> [CH] fiix liq belly examine not saving

- code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
> [CH] Cocoon Spin Freedom

- code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/positive.dm
> [CH] Weaver Attempt 2

- code/modules/env_message/env_message.dm
- code/modules/mob/living/bot/bot.dm
> [CH] bots need to reach the target

- code/modules/mining/shelter_atoms_vr.dm
- maps/offmap_vr/common_offmaps.dm
- modular_chomp/code/modules/mob/living/silicon/robot/dogborg/dog_modules.dm
> [CH] rebalance melee explo borg

- tgui/packages/tgui-panel/package.json
- tgui/packages/tgui/package.json
- tgui/yarn.lock
> [CH] Bump dompurify from 2.5.3 to 2.5.4 in /tgui

- code/modules/organs/pain.dm
- code/modules/reagents/reagents/food_drinks.dm
- code/modules/reagents/reagents/medicine.dm
> [CH] custom_pain makes you actually be in pain

- code/modules/organs/pain.dm
- code/modules/reagents/reagents/food_drinks.dm
- code/modules/reagents/reagents/medicine.dm
> [CH] Fixes too much hallos damage being taken

- modular_chomp/maps/overmap/om_ships/sdf_corvette-10x17.dmm
- modular_chomp/maps/overmap/om_ships/sdf_corvette.dmm
> [CH] fixes atmos for SDF

- code/modules/reagents/reagent_containers/patch.dm
> [CH] undo chem blood patches

- modular_chomp/code/modules/mining/shelters_ch.dm
> [CH] file pathing fix for superpose pod

- modular_chomp/code/modules/mob/living/carbon/human/species/station/traits/negative.dm
> [CH] Fixes Onelife trait

- code/game/jobs/jobs.dm
> [CH] Fixes Brig Physician being uselectable

- code/modules/mob/living/silicon/robot/sprites/civilian.dm
> [VR] Fix service drone

- code/modules/eventkit/generic_objects/generic_item.dm
- code/modules/eventkit/generic_objects/generic_structure.dm
- code/modules/mob/living/carbon/human/species/lleill/hanner.dm
> [VR] Generic item/structure fixes

- tgui/packages/tgui/interfaces/Canvas.tsx
> [VR] Massively improve painting experience

- code/modules/client/preference_setup/loadout/loadout_accessories.dm
> [VR] Add plushies to loadout!

- code/modules/admin/modify_robot.dm
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotComponent.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/types.ts
> [VR] some component stuff

- tgui/packages/tgui/interfaces/Pda/pda_screens/pda_main_menu.tsx
- tgui/packages/tgui/styles/interfaces/Pda.scss
- tgui/packages/tgui/styles/main.scss
> [VR] Add a transition effect to opening PDA apps and color to flashlight

- code/datums/datacore.dm
- code/game/objects/items/weapons/id cards/station_ids.dm
> [VR] Hanner Concealment

- code/game/objects/effects/decals/Cleanable/reagent_ch.dm
- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon_ch.dm
- code/modules/mob/living/simple_mob/subtypes/vore/goia_ch.dm
- code/modules/vore/fluffstuff/custom_clothes_yw.dm
> [CH] Zorgoia improvments

- code/game/turfs/simulated/water.dm
- code/modules/mob/living/carbon/human/human_movement.dm
> [VR] Flying over water/snow does not slow

- code/game/machinery/portable_turret.dm
> [CH] fix turret targeting

- maps/southern_sun/southern_cross-1.dmm
- maps/southern_sun/southern_cross-2.dmm
- maps/southern_sun/southern_cross-3.dmm
> [CH] Various map fixes!

- code/modules/mob/living/carbon/human/update_icons.dm
> [CH] Disabling bellysprite plane for now.

- code/__defines/tgs.dm
> [CH] trusted level

- maps/southern_sun/overmap/sectors.dm
- maps/southern_sun/southern_cross-1.dmm
- maps/southern_sun/southern_cross-2.dmm
- maps/southern_sun/southern_cross-3.dmm
- maps/southern_sun/southern_cross-9.dmm
- maps/southern_sun/southern_cross_defines.dm
- maps/southern_sun/southern_cross_presets.dm
> [CH] various map changes

- code/game/objects/effects/decals/crayon.dm
- code/game/objects/items/crayons.dm
- code/game/turfs/simulated/floor_attackby.dm
- code/game/turfs/simulated/wall_attacks.dm
- code/game/turfs/turf.dm
- code/modules/persistence/datum/persistence_datum.dm
- code/modules/persistence/effects/filth.dm
- code/modules/persistence/effects/graffiti.dm
- code/modules/persistence/effects/trash.dm
> [CH] Graffitis now take into account where on the tile you click

- .github/workflows/ci.yml
> [CH] changes back some CI changes (#9032)

- .github/workflows/update_tgs_dmapi.yml
> [CH] Create TGS DMAPI Update Job

- code/modules/organs/blood.dm
- code/modules/projectiles/guns/projectile_ch.dm
- code/modules/reagents/reagents/_reagents.dm
- code/modules/vore/eating/living_vr.dm
> [CH] some runtimes

- modular_chomp/code/game/machinery/food_replicator.dm
> [CH] Food Replicator fixes

- maps/southern_sun/southern_cross-1.dmm
- maps/southern_sun/southern_cross-2.dmm
- maps/southern_sun/southern_cross-3.dmm
> [CH] Southern Sun Map fixes! 1.4

- code/modules/surgery/surgery.dm
> [VR] Adds 3 second delay to amputations

- code/modules/client/preference_setup/loadout/gear_tweaks.dm
> [VR] we load it from a file, that path might no longer exist

- code/game/objects/effects/decals/posters/posters.dm
> [VR] Smol poster fix

- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon.dm
> [VR] fix random colour

- bin/tgui-fix.cmd
- tools/build/build.js
> [VR] Add tgui fix target

- code/modules/awaymissions/redgate.dm
- maps/redgate/laserdome.dmm
> [VR] Laserdome Improvements

- code/modules/vore/eating/living_vr.dm
> [VR] those should have a key... else no player chars

- tgui/packages/tgui/components/Button.tsx
> [VR] buttons no longer steal focus

- code/datums/supplypacks/engineering.dm
> [VR] allows to order more deuterium if needed

- code/modules/admin/modify_robot.dm
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotAccess.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotComponent.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotModules.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotPKA.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotRadio.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotUpgrades.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/index.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/types.ts
> [VR] ai syncing / unsyncing in modify robot

- code/modules/admin/modify_robot.dm
- code/modules/admin/verbs/modify_robot.dm
> [VR] fix the modify robot admin section for the ert channel

- code/modules/organs/organ.dm
- code/modules/surgery/robotics.dm
> [VR] Posibrain and drone intelligence surgery fixes

- code/game/objects/items/devices/scanners/sleevemate.dm
> [VR] Lets sleevemates scan patients in dogborg sleepers

- code/modules/recycling/conveyor2.dm
> [VR] Conveyors no longer move janitor dirt huds

- code/game/objects/effects/decals/crayon.dm
> [CH] Makes sure there's an actual icon before attempting to Blend()

- code/modules/vore/chat_healthbars.dm
> [VR] Print your own healthbar as prey

- code/modules/admin/verbs/pray.dm
> [VR] Fixes Prayers

- code/__defines/mobs.dm
- code/game/objects/structures/alien/alien.dm
- code/modules/materials/materials/organic/resin.dm
- code/modules/mob/living/carbon/human/species/station/replicant_crew.dm
- code/modules/organs/subtypes/replicant.dm
- code/modules/ventcrawl/ventcrawl.dm
- vorestation.dme
> [VR] Replicant Species

- code/modules/vore/eating/silicon_vr.dm
> [VR] Allow harm-intent disabling AI holograms

- code/_helpers/type2type.dm
- code/datums/looping_sounds/_looping_sound.dm
- code/modules/client/preference_setup/general/02_language.dm
- code/modules/client/preference_setup/general/03_body.dm
- code/modules/client/preference_setup/general/04_equipment.dm
- code/modules/client/preference_setup/loadout/loadout.dm
- code/modules/client/preference_setup/occupation/occupation.dm
- code/modules/client/preference_setup/skills/skills.dm
- code/modules/client/preference_setup/vore/07_traits.dm
- code/modules/client/preference_setup/vore/08_nif.dm
> [VR] de-reference save_data lists

- code/__defines/_planes+layers_vr.dm
- code/__defines/mobs_vr.dm
- code/modules/mob/dead/observer/login.dm
- code/modules/mob/mob_planes_vr.dm
- code/modules/nifsoft/software/13_soulcatcher.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/soulcatcher.dm
- modular_chomp/code/modules/vore/eating/soulcatcher_mob.dm
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSoulcatcher.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSoulcatcherSettings/GlobalSettings.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/types.ts
> [CH] SR testing

- code/modules/mob/living/silicon/robot/robot_modules/station.dm
> [CH] add combifan to engiborgs

- maps/southern_sun/southern_cross-1.dmm
- maps/southern_sun/southern_cross-2.dmm
- maps/southern_sun/southern_cross-3.dmm
> [CH] Southern Sun Map fixes1.5

- modular_chomp/code/game/objects/items/weapons/id_cards.dm
> [CH] sanity checks robot ID

- modular_chomp/code/game/objects/items/weapons/id_cards.dm
> [CH] better way for that

- code/datums/chat_message.dm
- code/modules/client/preference_setup/general/02_language.dm
> [VR] Allow choosing your own runechat color

- code/modules/organs/blood.dm
> [VR] Heart surgery is real

- code/modules/mob/say_ch.dm
> [CH] fix old input naming

- code/modules/client/preferences/types/misc.dm
- code/modules/mob/living/say.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/misc.tsx
> [VR] Automatic Punctuation pref

- code/modules/mob/new_player/sprite_accessories_taur_vr.dm
> [VR] fix up ch belly issues

- code/modules/admin/player_effects.dm
- tgui/packages/tgui/interfaces/PlayerEffects/PlayerEffectsTabs/ControlFixes.tsx
- tgui/packages/tgui/interfaces/PlayerEffects/PlayerEffectsTabs/ControlSmites.tsx
> [VR] Mob tf smite

- code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
- code/modules/mob/living/silicon/robot/robot_modules/station.dm
> [VR] Engiborg stasis clamp

- code/modules/admin/player_effects.dm
- code/modules/client/client procs.dm
- modular_chomp/code/modules/emotes/definitions/audiable.dm
> [CH] don't assume it's a human

- code/game/objects/items/weapons/id cards/cards.dm
> [VR] sanity checks robot ID spawns

- code/controllers/subsystems/mail_ch.dm
- code/game/objects/items/mail_ch.dm
- modular_chomp/code/game/objects/items/target_toy.dm
- vorestation.dme
> [CH] Mail Update

- code/modules/client/preference_setup/general/02_language.dm
> [CH] Deconf

- maps/southern_sun/southern_cross-1.dmm
- maps/southern_sun/southern_cross-2.dmm
- maps/southern_sun/southern_cross-3.dmm
> [CH] More fixes

- code/modules/client/preferences/migrations/15_nif_path.dm
- code/modules/client/preferences_savefile.dm
- vorestation.dme
> [VR] Add a savefile migration to remove the /device from nif paths

- code/modules/mob/living/silicon/robot/analyzer.dm
- code/modules/recycling/sortingmachinery.dm
- code/modules/shuttles/landmarks.dm
> [VR] Fixes missing textures

- code/modules/mob/living/simple_mob/subtypes/vore/horse.dm
> [CH] Missing kelpie init check

- code/modules/mob/living/simple_mob/subtypes/vore/horse.dm
> [CH] Revert "Missing kelpie init check"

- code/game/objects/items/devices/body_snatcher_vr.dm
- code/modules/mob/living/carbon/human/species/lleill/hanner.dm
- code/modules/mob/living/carbon/human/species/lleill/lleill_items.dm
- code/modules/mob/living/simple_mob/subtypes/vore/dominated_brain.dm
- code/modules/mob/living/simple_mob/subtypes/vore/morph/morph.dm
- code/modules/mob/living/simple_mob/subtypes/vore/vore.dm
- code/modules/resleeving/infocore_records.dm
- code/modules/resleeving/machines.dm
- code/modules/vore/chat_healthbars.dm
- code/modules/vore/eating/living_vr.dm
- code/modules/vore/eating/mob_vr.dm
- code/modules/vore/eating/vore_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- code/modules/vore/mouseray.dm
- tgui/packages/tgui/interfaces/VorePanel/VoreUserPreferences.tsx
- tgui/packages/tgui/interfaces/VorePanel/VoreUserPreferencesTabs/VoreUserPreferencesMechanical .tsx
- tgui/packages/tgui/interfaces/VorePanel/types.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreUserPreferences.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreUserPreferencesTabs/VoreUserPreferencesMechanical.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/types.ts
> [VR] Allow printing whitelisted bodies, but resleeve lock them by force

- code/modules/mob/living/carbon/human/human.dm
> [VR] don't have nifs stick out of heads

- code/modules/paperwork/faxmachine.dm
> [VR] stop fax flicking to copier icon

- .vscode/tasks.json
> [VR] Add vscode tasks to force-compile a specific map

- maps/southern_cross/southern_cross-2.dmm
> [CH] Fixes tape spawning in place of recording tape

- code/modules/vore/eating/belly_obj_ch.dm
- code/modules/vore/eating/belly_obj_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
- modular_chomp/code/modules/vore/eating/exportpanel_ch.dm
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyInteractions.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/types.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportBellyString.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/types.ts
> [CH] Add option to the interactions panel to trigger the belch emote on prey resisting

- modular_chomp/code/modules/planet/sif.dm
> [CH] Fixes anomalous weather imminent_transition_message

- code/game/objects/items/mail_ch.dm
> [CH] fix some mail stuff

- code/modules/mob/living/simple_mob/subtypes/vore/plants_ch/pitcher.dm
> [CH] properly add and remove from the list

- code/modules/resleeving/computers.dm
- tgui/packages/tgui/interfaces/BodyScanner/BodyScannerMainOccupant.tsx
- tgui/packages/tgui/interfaces/BodyScanner/BodyScannerMainOrgansExternal.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/MedicalRecordsList.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/MedicalRecordsMedbots.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/MedicalRecordsOptions.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/MedicalRecordsViewGeneral.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/MedicalRecordsViewMedical.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/MedicalRecordsViruses.tsx
- tgui/packages/tgui/interfaces/MedicalRecords/index.tsx
- tgui/packages/tgui/interfaces/OperatingComputer/OperatingComputerOptions.tsx
- tgui/packages/tgui/interfaces/OperatingComputer/OperatingComputerPatient.tsx
- tgui/packages/tgui/interfaces/OperatingComputer/index.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/BodyRecordModal.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/MindRecordModal.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsoleCoreDump.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsoleElements.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsolePodGrowers.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsolePodSleevers.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsolePodSpods.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsoleRecords.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/ResleevingConsoleStatus.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/index.tsx
- tgui/packages/tgui/interfaces/ResleevingConsole/types.ts
- tgui/packages/tgui/styles/interfaces/ResleevingConsole.scss
- tgui/packages/tgui/styles/main.scss
> [VR] Medical UI fixes and tweaks

- code/_onclick/hud/robot.dm
- code/datums/chat_message.dm
- code/modules/economy/cash_register.dm
- tgui/packages/tgui/interfaces/AssemblyTimer.tsx
> [VR] fix timer window

- code/game/objects/items/mail_ch.dm
> [CH] move the envelope color to update_icon

- code/game/objects/effects/decals/Cleanable/humans.dm
> [VR] prevent blood overlays from stacking up

- tgui/packages/tgui-panel/reconnect.tsx
- tgui/packages/tgui-panel/styles/components/Notifications.scss
> [VR] Move tgui panel notifications to top (tgstation/tgstation#85084)

- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
> [CH] updating chest transparency toggle to be head instead. better for slime synths.

- code/game/objects/items/weapons/storage/storage.dm
> [CH] Fix ghosts being able to spam sounds to players.

- tgui/packages/tgui/interfaces/ExosuitFabricator/Queue.tsx
> [VR] fixes some issues due to name mapping

- code/game/objects/items/devices/tvcamera.dm
> [CH] Bodycam view update on move

- code/modules/events/ion_storm.dm
- code/modules/mob/living/silicon/robot/robot_remote_control.dm
> [CH] keep shells in sync with AI

- code/game/objects/items/mail_ch.dm
> [CH] Removes a default object from junk mail

- code/modules/persistence/effects/filth.dm
> [CH] check that as well

- code/modules/vote/vote_verb.dm
> [CH] Places the new vote verbs in their rightful place

- code/modules/food/glass/bottle_potion.dm
- code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
- code/modules/mob/living/simple_mob/subtypes/vore/goia_ch.dm
- code/modules/persistence/effects/filth.dm
> [CH] color check that

- code/modules/reagents/reagents/food_drinks.dm
> [VR] Fixes bad affect_ingest paths

- code/modules/reagents/reactions/instant/drinks.dm
> [VR] Fixes bad decaf reactions

- code/game/objects/items/devices/communicator/communicator.dm
- code/modules/pda/pda.dm
- code/modules/projectiles/guns/projectile.dm
- code/modules/projectiles/guns/projectile_ch.dm
> [VR] Fixes wrist PDA runtiming when firing guns

- code/controllers/autotransfer.dm
- code/controllers/subsystems/ticker.dm
- code/modules/admin/admin_verb_lists_vr.dm
> [VR] Fixes crew transfer votes not starting

- code/__defines/dcs/signals.dm
- code/controllers/subsystems/throwing.dm
- code/datums/riding.dm
- code/game/area/areas.dm
- code/game/atoms.dm
- code/game/mecha/combat/fighter.dm
- code/game/objects/items/weapons/extinguisher.dm
- code/game/turfs/turf.dm
- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/holodeck/HolodeckControl.dm
- code/modules/looking_glass/lg_console.dm
- code/modules/mob/animations.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/carbon/human/human_movement_ch.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_movement.dm
- code/modules/mob/mob_movement.dm
- code/modules/multiz/movement.dm
- code/modules/power/gravitygenerator_vr.dm
- code/modules/shuttles/shuttle.dm
- modular_chomp/code/datums/components/squeak.dm
- modular_chomp/code/datums/elements/footstep.dm
- modular_chomp/code/datums/elements/slosh.dm
- modular_chomp/code/modules/mob/living/silicon/robot/robot_movement.dm
> [VR] Fixes space drift, renames has_gravity()

- code/modules/reagents/machinery/chem_master.dm
- tgui/packages/tgui/interfaces/ChemMaster/ChemMasterProductionChemical.tsx
> [VR] Chem master 2x bottle option

- tgui/packages/tgui/components/NanoMap.tsx
- tgui/packages/tgui/styles/components/NanoMap.scss
> [VR] Convert NanoMap to TSX and fix a bunch of bugs

- code/__defines/span_vr.dm
- code/game/gamemodes/changeling/generic_equip_procs.dm
- code/game/gamemodes/changeling/powers/armblade.dm
- code/game/gamemodes/changeling/powers/armor.dm
- code/game/gamemodes/changeling/powers/bioelectrogenesis.dm
- code/game/gamemodes/changeling/powers/rapid_regen.dm
- code/game/machinery/pipe/construction.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/adminpm.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/integrated_electronics/core/assemblies/generic.dm
- code/modules/mentor/mentor.dm
- code/modules/mentor/mentorhelp.dm
- code/modules/power/port_gen_vr.dm
- tgui/packages/tgui-panel/chat/constants.ts
- tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
- tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
- tgui/packages/tgui-panel/styles/tgchat/chat-vchatdark.scss
- tgui/packages/tgui-panel/styles/tgchat/chat-vchatlight.scss
> [VR] fix admin and mentor PMs

- code/modules/vore/eating/belly_obj_vr.dm
> [CH] fix autotransfer dest placeholder

- code/game/jobs/job/medical_ch.dm
> [CH] Allows geneticists to gain PTO

- code/game/objects/items/robot/robot_parts.dm
- code/global.dm
> [VR] Enable research module / prevent AI shells from building more AI shells

- code/modules/vote/vote_datum.dm
- code/modules/vote/vote_verb.dm
> [VR] span_warning for vote messages

- modular_chomp/code/modules/mob/new_player/sprite_accessories_extra.dm
- tools/github-actions/nanomap-renderer-invoker.sh
> [CH] render SC again

- code/game/objects/items/weapons/storage/bags.dm
> [VR] lightens the slowdown from chemistry bags

- modular_chomp/code/datums/crafting/tyr_tribal.dm
> [CH] fix missing subcat

- code/datums/supplypacks/engineering.dm
- modular_chomp/code/modules/reagents/reactions/instant/instant.dm
> [CH] SMES coil price reduction plus some new reactions

- code/modules/admin/admin_verbs_vr.dm
- code/modules/library/lib_machines.dm
- code/modules/mob/new_player/poll.dm
> [CH] deletes some not deleted db quries

- SQL/DBSchema.sql
> [CH] updates database schema

- code/game/jobs/job/captain_vr.dm
- code/game/jobs/job/civilian_vr.dm
- code/game/jobs/job/engineering_vr.dm
- code/game/jobs/job/exploration_vr.dm
- code/game/jobs/job/medical_vr.dm
- code/game/jobs/job/science_vr.dm
- code/game/jobs/job/security_vr.dm
- code/game/jobs/job/silicon_vr.dm
> [CH] Required time adjustments

- code/modules/vore/eating/belly_obj_vr.dm
- modular_chomp/code/modules/asset_cache/belly_assets.dm
- vorestation.dme
> [CH] belly image datums

- code/modules/paperwork/paper_bundle.dm
> [VR] cut old overlays on paperstack

- code/modules/research/designs/bio_devices_vr.dm
> [VR] renames nif design

- code/modules/food/food/lunch.dm
> [VR] fix improper food greartweaks

- code/modules/mob/living/simple_mob/simple_mob_vr.dm
> [VR] forwards rejuvenate icon update call for simple mobs

- code/modules/food/recipe.dm
> [VR] up ports endless mouseburger fix

- code/modules/economy/ATM.dm
- tgui/packages/tgui/interfaces/AutomatedTellerMachine.tsx
- tgui/packages/tgui/styles/interfaces/AutomatedTellerMachine.scss
- tgui/packages/tgui/styles/main.scss
> [VR] Convert ATM to TGUI

- code/modules/mob/living/living.dm
- code/modules/power/lighting.dm
> [VR] tele patch

- code/modules/power/smes.dm
> [VR] SMES Fix

- code/modules/clothing/under/accessories/accessory_vr.dm
- tgui/packages/tgui/interfaces/ShockCollar.tsx
> [VR] TGUI Shock Collar

- code/modules/reagents/reagents/medicine.dm
> [VR] Makes leporazine respect species body temp

- code/modules/recycling/disposal.dm
> [VR] Adds forced eject verb to disposals

- tgui/packages/tgui/interfaces/ICAssembly/CircuitComponent.tsx
- tgui/packages/tgui/interfaces/ICAssembly/Plane.tsx
- tgui/packages/tgui/interfaces/ICAssembly/types.ts
> [VR] Remove traces of click to select port

- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/tgui/modules/crew_manifest.dm
- tgui/packages/tgui/interfaces/CrewManifest.tsx
> [VR] Unify TGUI crew manifest across lobby and ghosts, make it a true table

- code/modules/client/preference_setup/general/03_body.dm
> [VR] Disables random hair

- code/modules/modular_computers/file_system/programs/generic/fishing.dm
- tgui/packages/tgui/interfaces/FishingMinigame.tsx
- tgui/packages/tgui/interfaces/NtosFishing.tsx
- tgui/packages/tgui/styles/interfaces/FishingMinigame.scss
- tgui/packages/tgui/styles/main.scss
- vorestation.dme
> [VR] Add a new fishing minigame to NTOS

- code/modules/vore/eating/belly_messages.dm
- code/modules/vore/eating/belly_obj_vr.dm
- tgui/packages/tgui/interfaces/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyDescriptions.tsx
- tgui/packages/tgui/interfaces/VorePanel/constants.ts
- tgui/packages/tgui/interfaces/chompstation/VorePanel/VoreSelectedBellyTabs/VoreSelectedBellyDescriptions.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanel/constants.ts
> [VR] Add digested prey count belly format text

- code/modules/vore/eating/living_vr.dm
- html/browser/common.css
> [VR] Dark-mode color-coded mechanical vore preferences UI

- code/modules/client/client procs.dm
> [VR] adds a verb to print playtime

- code/game/objects/items/devices/communicator/communicator.dm
- code/modules/pda/pda.dm
- code/modules/projectiles/guns/projectile.dm
> [VR] gunshot residue should only be on clothing/human

- modular_chomp/maps/overmap/om_ships/lonehomeship-20x13.dmm
> [CH] Fixes Lone Home Shuttle door and sensor areas

- code/modules/clothing/spacesuits/rig/rig_tgui.dm
- tgui/packages/tgui/interfaces/RIGSuit/RIGSuitStatus.tsx
> [VR] Add button to access tank settings in RIGs

- code/game/objects/items/weapons/implants/implant_vr.dm
> [CH] Fix the size implant having it's own clamping.

- code/modules/client/client procs.dm
- code/modules/client/preferences/types/ui.dm
- code/modules/mob/typing_indicator.dm
- code/modules/tgui_input/say_modal/modal.dm
- tgui/packages/tgui-say/TguiSay.tsx
- tgui/packages/tgui-say/constants.ts
- tgui/packages/tgui-say/helpers.ts
- tgui/packages/tgui-say/styles/window.scss
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ui.tsx
> [VR] Improve tgui say experience with extra control prefs

- maps/southern_cross/submaps/gateway/snowfield_ch.dm
- maps/southern_sun/submaps/gateway/snowfield_ch.dm
> [CH] clean up snowfield

- maps/southern_cross/overmap/planets/tyr/tyr.dm
> [CH] Makes the tyr caverns caverns

- code/modules/food/food/drinks.dm
> [VR]  Mob-food vore fix

- code/modules/virus2/admin.dm
> [VR]  fix virus VV

- code/game/objects/effects/mines.dm
> [VR]  Patches rare qdel loop on mines

- code/game/mecha/equipment/tools/passenger.dm
- code/game/mecha/equipment/tools/sleeper.dm
> [VR]  Allows resisting out of mech passenger compartments and sleepers

- code/game/mecha/equipment/tools/passenger.dm
- code/game/objects/effects/mines.dm
- code/modules/clothing/spacesuits/rig/modules/modules.dm
> [VR] add missing triggered and some mirror fixes

- code/modules/mob/living/carbon/human/life_ch.dm
> [CH] chomp override on rads

- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/southern_cross-3.dmm
> [CH] Fixes some map errors

- code/modules/client/preference_setup/general/06_flavor.dm
- code/modules/food/kitchen/microwave.dm
- code/modules/vore/eating/vorepanel_vr.dm
> [VR] some more small things

- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/southern_cross-3.dmm
> [CH] Revert "Fixes some map errors"

- code/game/machinery/newscaster.dm
- code/game/objects/items.dm
- code/game/objects/items/devices/scanners/health.dm
- code/game/objects/structures/watercloset.dm
- code/modules/mob/living/silicon/robot/inventory.dm
- tgui/packages/tgui/interfaces/Newscaster/NewscasterViewSelected.tsx
- tgui/packages/tgui/interfaces/Newscaster/types.ts
> [VR] some fixes

- code/game/machinery/doors/airlock.dm
> [VR]  Hold a door open without standing in it

- code/__defines/cooldowns.dm
- code/modules/overmap/overmap_object.dm
- code/modules/overmap/ships/computers/helm.dm
- code/modules/overmap/ships/ship.dm
- code/modules/overmap/turfs.dm
- code/modules/tgui/modules/overmap.dm
- tgui/packages/tgui/interfaces/OvermapHelm.tsx
> [VR]  ByondUI Overmap Navigation

- code/datums/observation/unequipped.dm
- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/mining/kinetic_crusher.dm
- code/modules/organs/internal/augment.dm
> [VR]  Fix a small runtime in actions when dropping rigs

- maps/southern_cross/southern_cross-2.dmm
- maps/southern_cross/southern_cross-3.dmm
> Revert "Revert "Fixes some map errors""

- code/modules/mob/new_player/new_player.dm
- code/modules/tgui/modules/_base.dm
- code/modules/tgui/modules/late_choices.dm
- tgui/packages/tgui/interfaces/LateChoices.tsx
- vorestation.dme
> [VR] Convert late spawn UI to TGUI

- code/modules/mob/living/simple_mob/subtypes/vore/leopardmander_ch.dm
> [CH] Fixes leopardmander autotransfer
