- code/__defines/_helpers.dm
- code/__defines/_lists.dm
- code/__defines/misc.dm
- code/__defines/subsystems.dm
- code/_helpers/_lists.dm
- code/controllers/configuration/entries/general.dm
- code/controllers/subsystems/timer.dm
- code/datums/datum.dm
- config/example/logging.txt
> [VR]  Timer subsystem update

- html/statbrowser.css
- html/statbrowser.html
- html/statbrowser.js
- tgui/packages/tgui-panel/settings/SettingsPanel.tsx
- tgui/packages/tgui-panel/settings/SettingsStatPanel.tsx
- tgui/packages/tgui-panel/settings/constants.ts
- tgui/packages/tgui-panel/settings/middleware.ts
- tgui/packages/tgui-panel/settings/reducer.ts
> [VR]  Statpanel styles

- code/__defines/dna.dm
- code/game/dna/dna2.dm
- code/game/dna/dna2_helpers.dm
- code/modules/client/preference_setup/general/03_body.dm
- code/modules/mob/dead/corpse.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/mob/living/carbon/human/species/lleill/hanner.dm
- code/modules/mob/living/carbon/human/species/lleill/lleill.dm
- code/modules/mob/living/carbon/human/species/species_shapeshift_vr.dm
- code/modules/mob/living/carbon/human/species/station/prometheans_vr.dm
- code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
- code/modules/mob/living/carbon/human/species/station/replicant_crew.dm
- code/modules/mob/living/carbon/human/species/virtual_reality/avatar.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/new_player/sprite_accessories.dm
- code/modules/mob/new_player/sprite_accessories_ear.dm
- code/modules/resleeving/designer.dm
- code/modules/tgui/modules/appearance_changer.dm
- code/modules/vore/fluffstuff/custom_clothes_vr.dm
- code/modules/vore/persist/persist_vr.dm
- tgui/packages/tgui/interfaces/AppearanceChanger/AppearanceChangerBody.tsx
- tgui/packages/tgui/interfaces/AppearanceChanger/AppearanceChangerDetails.tsx
- tgui/packages/tgui/interfaces/AppearanceChanger/types.ts
- tgui/packages/tgui/interfaces/BodyDesigner/types.ts
Исходный ПР: 9329
:cl:
add: В Редактор персонажа добавлен пункт "Рога", функционирующий как второй слот ушей персонажа.
/:cl:
> [VR]  Adds a second ear slot.

- code/modules/clothing/clothing.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/spacesuits/spacesuits.dm
- code/modules/clothing/spacesuits/void/void.dm
Исходный ПР: 9328
:cl:
qol: Шлемы скафандров теперь можно надевать поверх других элементов одежды на голове.
/:cl:
> [VR]  Add support for deploying space helmets over top of other helmets

- modular_chomp/code/modules/halloween/items.dm
> [CH] Fixes halloween candy bowls

- code/game/objects/items.dm
- code/modules/mining/mine_turfs.dm
- code/modules/xenoarcheaology/finds/find_spawning.dm
- code/modules/xenoarcheaology/finds/finds.dm
> [CH] Xenoarch order

- tgui/packages/tgui/interfaces/VorePanelExport/VorePanelExportDownload.tsx
- tgui/packages/tgui/interfaces/VorePanelExport/types.ts
> [CH] sanity checks some vorepanel things

- html/statbrowser.js
> [VR]  focus statpanel content on tab change

- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_ui.dm
- tgui/packages/tgui/components/ColorBox.tsx
- tgui/packages/tgui/interfaces/Robotact/StatusScreen.tsx
- tgui/packages/tgui/interfaces/Robotact/types.ts
Исходный ПР: 9338
:cl:
add: Роботы теперь могут выбирать цвет своего фонаря.
\:cl:
> [VR]  adds custom light option for robots

- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/VorePanelExportDownload.tsx
- tgui/packages/tgui/interfaces/chompstation/VorePanelExport/types.ts
> [VR]  sanity checks some things in case we really have no bellies

- code/modules/reagents/reagents/vore_vr.dm
> [VR]  Fix rainbow toxin overdose

- code/controllers/subsystems/statpanel.dm
- code/datums/mind.dm
- code/modules/mob/living/carbon/human/species/station/prommie_blob.dm
- code/modules/mob/living/carbon/human/species/virtual_reality/avatar.dm
- code/modules/mob/mob_defines.dm
- modular_chomp/code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
- modular_chomp/code/modules/mob/living/living.dm
- modular_chomp/code/modules/mob/living/simple_mob/teppi.dm
> [CH] fix multiple issues

- code/modules/clothing/clothing.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/spacesuits/spacesuits.dm
- code/modules/clothing/spacesuits/void/void.dm
> [VR] Revert " Add support for deploying space helmets over top of other helmets"

- modular_chomp/code/modules/mob/living/silicon/robot/sprites/command.dm
- modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/spacecritters.dm
> [CH] fix command nika sprite

- code/game/objects/items/devices/whistle.dm
- code/modules/detectivework/tools/uvlight.dm
> [VR]  Fixes broken sprites

- code/game/objects/items/weapons/circuitboards/machinery/fluidpump.dm
- code/modules/reagents/machinery/pump.dm
Исходный ПР: 9385
🆑
fix: Исправлена работа жидкостной помпы.
balance: Уменьшена скорость генерации веществ жидкостной помпы.
/:cl:
> [VR]  Fixes fluid pump

- code/modules/admin/player_effects.dm
- tgui/packages/tgui/interfaces/PlayerEffects/PlayerEffectsTabs/ControlSmites.tsx
Исходный ПР: 9383
🆑
rscadd: Новый способ кары - Превращение в предмет.
/:cl:
> [VR]  Item TF smite

- code/modules/ai/ai_holder_subtypes/simple_mob_ai.dm
- code/modules/ai/ai_holder_targeting.dm
- code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
Исходный ПР: 9386
🆑
rscadd: ИИ некоторых наёмников теперь позволяет подкрадываться к ним со спины.
/:cl:
> [VR]  Metal Vore Solid

- code/__defines/jobs.dm
- code/game/jobs/job/engineering_vr.dm
- code/game/jobs/job/science_vr.dm
> [VR]  Add two new alt titles: Software Engineer, Computer Technician

- code/datums/chat_message.dm
- code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/phorogenic.dm
> [VR]  migrate chat messages and phoron spider to self deleting timer

- code/modules/admin/player_effects.dm
- code/modules/admin/verbs/smite.dm
> [CH] enables voremob for kin smite

- code/modules/admin/player_effects.dm
- code/modules/admin/verbs/smite.dm
> [CH] add it here too

- code/datums/chat_message.dm
> [CH] remove that flag

- code/controllers/configuration/entries/dbconfig.dm
- code/controllers/configuration/entries/game_options.dm
- code/controllers/subsystems/persist_vr.dm
- code/datums/chat_message.dm
> [CH] Massquery

- code/game/objects/items/devices/communicator/communicator.dm
- code/modules/mob/mob_planes_vr.dm
- modular_chomp/code/game/objects/effects/dark_growth.dm
- modular_chomp/code/modules/vore/eating/soulcatcher.dm
> [CH] clear some qdel refs

- code/game/machinery/partslathe_vr.dm
- code/game/objects/structures/railing.dm
- code/modules/research/circuitprinter.dm
- code/modules/research/protolathe.dm
- code/modules/tgui/modules/overmap.dm
> [VR]  prevent out of index access on tgui spamming the rd console

- code/modules/mentor/mentor.dm
> [VR]  fix f1 adminhelp

- tgui/packages/tgui/interfaces/SmartVend.tsx
Исходный ПР: 9406
🆑
fix: Изменено оформление названий продуктов в умных холодильниках.
/:cl:
> [VR]  Fix overflow in smartfrige, expand width a little

- modular_chomp/maps/southern_cross/southern_cross-3.dmm
- modular_chomp/maps/southern_cross/southern_cross-4.dmm
- modular_chomp/maps/~map_system/_map_selection.dm
> [CH] Revert "Halloweenifies the station"

- modular_chomp/code/modules/halloween/snacks.dm
Исходный ПР: 9411
:cl:
fix: В свежих яйцах больше не содержатся токсины. Они содержатся только в гнилых.
/:cl:
> [CH] Unrottens your eggs

- tgui/packages/tgui/interfaces/VorePanel/VoreInsidePanel.tsx
- tgui/packages/tgui/interfaces/VorePanel/index.tsx
- tgui/packages/tgui/interfaces/VorePanel/types.ts
> [VR]  fix the vorepanel

- code/datums/mutable_appearance.dm
- code/modules/admin/modify_robot.dm
- code/modules/mob/living/silicon/robot/component.dm
- code/modules/mob/living/silicon/robot/robot_damage.dm
- code/modules/power/cell.dm
- code/modules/power/cells/device_cells_vr.dm
- code/modules/power/cells/power_cells.dm
- code/modules/research/prosfab_designs.dm
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotComponent.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/ModifyRobotTabs/ModifyRobotComponentTabs.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/constants.ts
- tgui/packages/tgui/interfaces/ModifyRobot/index.tsx
- tgui/packages/tgui/interfaces/ModifyRobot/types.ts
Исходный ПР: 9412
🆑
add: Новые компоненты улучшений для роботов теперь позволяют увеличить запас здоровья вплоть до 370 ед, а также уменьшить затраты энергии.
/🆑
> [VR]  Robot upgrades

- code/game/objects/items/weapons/material/ashtray.dm
> [VR]  Makes ashtrays visible in SDMM

- code/modules/economy/vending_machines_vr.dm
> [VR]  New -> Init for Vending Machines

- code/game/objects/items/weapons/tools/crowbar.dm
Исходный ПР: 9399
🆑
balance: Урон красной монтировки увеличен с 6 до 10.
/:cl:
> [CH] red crowbar does more damage

- modular_chomp/code/modules/asset_cache/belly_assets.dm
> [CH] fix 2 missing asset datums

- code/controllers/subsystems/statpanel.dm
> [VR]  Restricts ahelp ticket view

- modular_chomp/maps/soluna_nexus/soluna_nexus-1.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-2.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-3.dmm
> [CH] Soluna Nexus Map Fixes 1.3

- code/modules/vehicles/rover_vr.dm
- code/modules/vehicles/vehicle.dm
> [VR]  fixes an invisibility exploit

- code/modules/events/meteors.dm
- code/modules/shieldgen/shield_gen.dm
> [CH] Revert "Undo meteor shield changes"

- code/modules/power/cell.dm
- modular_chomp/code/modules/power/cells/device_cells.dm
- modular_chomp/code/modules/power/cells/esoteric_cells.dm
> [CH] bunch of more cells

- modular_chomp/maps/soluna_nexus/soluna_nexus-1.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-2.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-3.dmm
> [CH] Soluna Nexus map fixes 1.4

- code/game/objects/effects/decals/Cleanable/humans.dm
- code/game/objects/items/devices/scanners/health.dm
- code/modules/reagents/reagents/virology.dm
Исходный ПР: 9449
🆑
qol: Взаимодействие с зараженной разметкой на полу теперь может привести к заражению вирусами.
qol: Уточнены описания лекарственных веществ.
/:cl:
> [VR]  Virology Patch 1

- code/game/objects/structures/props/machines.dm
- maps/redgate/cybercity.dmm
- maps/redgate/facility.dmm
Исходный ПР: 9448
:cl:
maptweak: В краснопространственных картах добавлены новые вирусологические машины.
/:cl:
> [VR]  Fixed virology themed redgate maps

- code/game/objects/items/devices/chameleonproj.dm
> [VR]  refactors chameleon projector

- code/modules/organs/blood.dm
> [VR]  Fixes non-contagious diseases not transferring on blood

- code/modules/clothing/under/accessories/accessory_vr.dm
> [VR]  Choker tweak

- code/game/machinery/contraband_scanner.dm
- vorestation.dme
Исходный ПР: 9457
:cl:
rscadd: Добавлен детектор контрабанды, издающий сигнал тревоги, если через него пройдёт персонаж с предметом из запрещённого списка.
/:cl:
> [VR]  Contraband Scanner

- code/game/machinery/camera/camera.dm
- code/game/objects/items/weapons/material/kitchen.dm
- maps/offmap_vr/common_offmaps.dm
- maps/redgate/eggnogtown.dmm
> [VR]  maptest redgate

- modular_chomp/maps/soluna_nexus/soluna_nexus-3.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus_areas.dm
> [CH] area should be sleep like on the global defines

- modular_chomp/maps/soluna_nexus/soluna_nexus-1.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-2.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-3.dmm
> [CH] Soluna Nexus Map fixes 1.5

- tgui/packages/tgui/interfaces/SmartVend.tsx
> [VR]  adds Search to smart vendors

- modular_chomp/maps/soluna_nexus/soluna_nexus-1.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-2.dmm
- modular_chomp/maps/soluna_nexus/soluna_nexus-3.dmm
> [CH] Soluna Nexus map fix 1.6

- code/_helpers/game.dm
> [VR]  Fixes recursive_content_check

- code/datums/diseases/advance/symptoms/fever.dm
- code/datums/diseases/advance/symptoms/flesh_eating.dm
- code/datums/diseases/advance/symptoms/heal.dm
- code/datums/diseases/advance/symptoms/shivering.dm
- code/modules/reagents/reagents/virology.dm
> [VR]  Virology Patch 3

- modular_chomp/maps/~map_system/_map_selection.dm
> [CH] Changes the selected to Southern Cross.

- code/__defines/faction.dm
- code/modules/mob/living/simple_mob/subtypes/vore/bigdragon_ch.dm
- code/modules/mob/living/simple_mob/subtypes/vore/goia_ch.dm
> [CH] some faction defines

- BUILD.cmd
- build.cmd
> [CH] rm duplicate build

- code/__defines/jobs.dm
- code/game/jobs/job/engineering_vr.dm
> [VR]  Salvage Tech Title

- code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
> [VR]  Allows non-custom species to take winged flight

- code/__defines/chemistry.dm
- code/game/objects/items/weapons/storage/bags.dm
- code/modules/reagents/machinery/grinder.dm
Исходный ПР: 9495
🆑
add: Сырые руды и многие материалы теперь можно перемолоть в вещества.
qol: Шлак теперь нельзя поместить в шахтёрскую сумку.
/:cl:
> [VR]  Ports grindable ores

- code/modules/client/verbs/advanced_who.dm
- code/modules/mob/dead/observer/observer.dm
> [VR]  Restricted aghosting and detailed advanced who to staff

- tgui/yarn.lock
> [CH] Bump cross-spawn from 7.0.3 to 7.0.6 in /tgui

- code/modules/mob/living/silicon/robot/robot.dm
> [VR]  Removes ability for research cyborgs to self-upgrade

- code/game/objects/items/devices/body_snatcher_vr.dm
- code/game/objects/items_vr.dm
- code/modules/vore/eating/living_vr.dm
- code/modules/vore/mouseray.dm
- modular_chomp/code/game/objects/items/devices/mind_binder.dm
> [CH] Binder/Snatcher OOC Escape

- code/modules/mob/living/silicon/robot/robot.dm
> [VR] Potential partial revert to borg self-upgrading restrictions

- modular_chomp/maps/overmap/space_pois/debris1_60x60.dmm
> [CH] places the right steel stack

- code/game/objects/items/weapons/cigs_lighters.dm
- code/game/objects/items/weapons/material/ashtray.dm
- code/modules/food/food/snacks.dm
Исходный ПР: 9508
🆑
add: Разумы, привязанные к кубам мартышек и прочих существ, теперь обретают контроль над появившимся существом.
add: Съеденные кубы существ поглощают и появившееся существо, если включены предпочтения Спонтанный хищник и Пищевой Vore.
/:cl:
> [CH] Item TF interactions with mob cubes and cigarettes

- code/controllers/subsystems/lighting.dm
- code/modules/lighting/lighting_corner.dm
- code/modules/lighting/lighting_overlay.dm
- code/modules/lighting/lighting_source.dm
- code/modules/lighting/lighting_turf.dm
- code/modules/lighting/sunlight_handler_ch.dm
Исходный ПР: 9268
🆑
fix: Оптимизация системы освещения.
/:cl:
> [VR]  Micro-opt lighting

- tools/github-actions/nanomap-renderer-invoker.sh
> [CH] enbale relic base rendering
