BastionOfEndeavor/BastionOfEndeavor2

code/game/jobs/job_controller.dm, code/modules/admin/verbs/buildmode.dm, code/modules/admin/verbs/randomverbs.dm
=> [ЗЕРКАЛО] Fixes some adminverb runtimes

code/modules/admin/admin_verb_lists_vr.dm, code/modules/client/preference_setup/global/setting_datums.dm, code/modules/client/preferences_toggle_procs.dm, code/modules/mob/mob_helpers.dm
=> [ЗЕРКАЛО] Some staff-specific pref staff

maps/expedition_vr/aerostat/aerostat_science_outpost.dmm
=> [ЗЕРКАЛО] Separates networks of cables on SD's outpost

code/modules/mob/dead/observer/observer.dm
=> [ЗЕРКАЛО] [MIRROR] A couple ghost fixes

code/modules/xenoarcheaology/finds/talking.dm
=> [ЗЕРКАЛО] Brings silence to the world of ghosts

code/modules/food/food/drinks/bottle.dm
=> [ЗЕРКАЛО] Fixes bottle throwing

code/modules/client/preference_setup/general/02_language.dm
=> [ЗЕРКАЛО] Fixes runtime with loading bad-saved langaugaes

code/modules/mob/living/carbon/human/species/station/xenochimera_trait_vr.dm
=> [ЗЕРКАЛО] Allows Xenochimeras to take Cocoon Spinner

code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm, code/modules/mob/living/simple_mob/subtypes/vore/vore.dm, code/modules/vore/eating/living_vr.dm, code/modules/vore/eating/vore_vr.dm, code/modules/vore/eating/vorepanel_vr.dm, code/modules/vore/mouseray.dm
=> [ЗЕРКАЛО] Allows Long Predatorial Reach to toggle modes.

code/modules/mob/living/silicon/robot/robot_modules/station.dm, code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
=> [ЗЕРКАЛО] Adjusts emagged booze

code/game/area/areas.dm, code/game/objects/items/weapons/storage/backpack_vr.dm, code/modules/events/prison_break.dm
=> [ЗЕРКАЛО] Fixes a few more runtimes.

code/game/machinery/rechargestation.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
=> [ЗЕРКАЛО] Add charger penalty to biofuel processors

code/modules/vore/eating/living_vr.dm
=> [ЗЕРКАЛО] Removes a redundant icon update

code/modules/client/preferences_vr.dm
=> [ЗЕРКАЛО] Fixes runtime with capture crystal pref

code/modules/mob/living/simple_mob/subtypes/animal/alien animals/spookyghost.dm
=> [ЗЕРКАЛО] Adds spookyghost sanity check

code/modules/mob/living/carbon/human/species/outsider/vox.dm, code/modules/mob/living/carbon/human/species/species_getters_vr.dm, code/modules/mob/living/carbon/human/species/species_vr.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm, code/modules/vore/eating/living_vr.dm
=> [ЗЕРКАЛО] Fixes belly air for phoron/nitrogen breathers

code/modules/client/client procs.dm
=> [ЗЕРКАЛО] Attempts to fix simplemob pref loading

maps/stellar_delight/stellar_delight2.dmm, maps/stellar_delight/stellar_delight3.dmm
=> [ЗЕРКАЛО] Changes to Bridge, HoP, and IAA offices

code/modules/mob/living/simple_mob/subtypes/animal/alien animals/startreader.dm, code/modules/vore/eating/vore_vr.dm
=> [ЗЕРКАЛО] Fixes two more runtimes hopefully

maps/groundbase/groundbase.dm, maps/groundbase/groundbase_events.dm, maps/stellar_delight/stellar_delight.dm, maps/stellar_delight/stellar_delight_events.dm, maps/tether/tether.dm, maps/tether/tether_events.dm, vorestation.dme
=> [ЗЕРКАЛО] Adds basic system to allow for map-specific events

code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/simple_mob/subtypes/vore/pakkun.dm
=> [ЗЕРКАЛО] Fixes pakkun stuff

code/modules/multiz/ladders.dm
=> [ЗЕРКАЛО] Makes ladder climb time variable

code/game/machinery/frame.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/weapons/circuitboards/machinery/kitchen_appliances.dm, code/modules/mob/new_player/sprite_accessories.dm, code/modules/mob/new_player/sprite_accessories_vr.dm
=> [ЗЕРКАЛО] Fixes a few bugs/runtimes

code/game/objects/items/weapons/storage/bags.dm
=> [ЗЕРКАЛО] Fixes runtime with sheet snatcher

code/game/machinery/cryo.dm, code/game/machinery/rechargestation.dm, code/game/objects/items/devices/scanners/health.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/taste.dm, code/modules/mob/mob_defines_vr.dm, code/modules/reagents/reactions/instant/instant_vr.dm, code/modules/reagents/reagent_containers/hypospray.dm, code/modules/reagents/reagents/medicine.dm, code/modules/reagents/reagents/medicine_vr.dm
=> [ЗЕРКАЛО] Radiation Rework

code/modules/mob/living/carbon/human/death_vr.dm, code/modules/mob/living/silicon/robot/dogborg/dog_sleeper_vr.dm
=> [ЗЕРКАЛО] Fixes dogborg inbuilt belly deaths not counting as vore deaths

code/datums/supplypacks/vending_refills_vr.dm, code/game/objects/random/mapping.dm, code/modules/economy/vending_refills.dm
=> [ЗЕРКАЛО] Removes hotfood vendors from station spawning

code/game/objects/explosion_recursive.dm
=> [ЗЕРКАЛО] Fixes recursive explosions

code/game/turfs/simulated/floor_types.dm
=> [ЗЕРКАЛО] Lighting Underlay Stacking Fix

code/modules/vore/resizing/resize_vr.dm
=> [ЗЕРКАЛО] Fixes micro pick-up temporary toggle to work properly

code/modules/power/port_gen_vr.dm, code/modules/xenoarcheaology/effects/teleport.dm
=> [ЗЕРКАЛО] Fixes teleport artifact not unbuckling mobs properly

code/modules/nifsoft/software/05_health.dm
=> [ЗЕРКАЛО] Fixes runtime with medichines deletion

code/modules/food/food/snacks_vr.dm
=> [ЗЕРКАЛО] Fixes ascended donk pocket

config/alienwhitelist.txt
=> [ЗЕРКАЛО] Add digi5 to Black-Eyed Shadekin whitelist

code/modules/vore/eating/vorepanel_vr.dm
=> [ЗЕРКАЛО] Buffs Vore

code/_onclick/hud/popups_vr.dm, code/game/machinery/recharger.dm, code/game/objects/items/weapons/storage/backpack.dm
=> [ЗЕРКАЛО] Fixes bluespace bag recursion disappearance

code/datums/supplypacks/munitions.dm, code/datums/uplink/visible_weapons.dm, code/game/objects/random/guns_and_ammo.dm, code/modules/projectiles/guns/projectile/shotgun.dm
=> [ЗЕРКАЛО] [MIRROR] Adds Sjorgen Inertial Shotgun (by H-H) (ABLE TO BE MERGED)

code/modules/holodeck/HolodeckObjects.dm, maps/cynosure/cynosure-2.dmm
=> [ЗЕРКАЛО] [MIRROR] pool swimwear locker names, holo floor/item names (ABLE TO BE MERGED) 

code/ATMOSPHERICS/datum_pipeline.dm
=> [ЗЕРКАЛО] [MIRROR] fix reactor pool heating up cooling pipes (ABLE TO BE MERGED) 

code/modules/client/preference_setup/traits/trait_defines.dm, code/modules/client/preference_setup/traits/traits.dm
=> [ЗЕРКАЛО] [MIRROR] Skips traits that aren't implemented yet. (ABLE TO BE MERGED) 

.vscode/extensions.json
=> [ЗЕРКАЛО] [MIRROR] un-recommends editorconfig for vscode (ABLE TO BE MERGED) 

code/modules/xenoarcheaology/effects/cellcharge.dm
=> [ЗЕРКАЛО] [MIRROR] Cellcharge artifact effect iterates over shorter lists (ABLE TO BE MERGED)

code/datums/uplink/medical.dm
=> [ЗЕРКАЛО] [MIRROR] Antag Uplink Medical Adjustments (ABLE TO BE MERGED)

code/datums/uplink/armor.dm
=> [ЗЕРКАЛО] [MIRROR] Uplink Armor Point Adjustments (ABLE TO BE MERGED) 

.github/workflows/render_nanomaps.yml
=> [ЗЕРКАЛО] GitHub Workflows security hardening

code/game/turfs/simulated/wall_types.dm
=> [ЗЕРКАЛО] Fixes conk rete walls

code/game/objects/micro_event.dm, vorestation.dme
=> [ЗЕРКАЛО] TOOL!

code/stylesheet.dm
=> [ЗЕРКАЛО] Fixes D'Rudak'Ar not having oldchat font

code/modules/mob/living/carbon/human/human_species_vr.dm
=> [ЗЕРКАЛО] i want to brutalize rats

code/modules/mob/living/carbon/human/human_movement.dm
=> [ЗЕРКАЛО] Removes old, janky-ass, unnecesary slowdown from numbing enzyme.

code/modules/multiz/movement.dm
=> [ЗЕРКАЛО] Allows simplemobs to climb lattices

code/game/objects/structures/ghost_pods/ghost_pods.dm
=> [ЗЕРКАЛО] ADMIN: EVENT

vorestation.dme
=> [ЗЕРКАЛО] Back to Tether

code/modules/mining/abandonedcrates.dm, code/modules/mining/abandonedcrates_vr.dm
=> [ЗЕРКАЛО] Adjusts abandoned crate content self-destruct

code/controllers/subsystems/ai.dm, code/controllers/subsystems/mobs.dm, code/modules/xenoarcheaology/effects/vampire.dm, code/modules/xenoarcheaology/finds/special.dm
=> [ЗЕРКАЛО] Fixes critical crash bugs

code/game/objects/items/devices/personal_shield_generator_vr.dm
=> [ЗЕРКАЛО] Fixes inability to use multitool on upgraded shields

code/game/mecha/equipment/tools/drill.dm, code/game/mecha/working/ripley.dm
=> [ЗЕРКАЛО] Makes mechas able to suck ore into boxes.

code/modules/mob/living/simple_mob/subtypes/vore/pakkun.dm
=> [ЗЕРКАЛО] Complicates Pakkuns

code/modules/mob/dead/observer/observer.dm
=> [ЗЕРКАЛО] Ghost default swap

code/modules/random_map/noise/ore.dm, maps/expedition_vr/aerostat/_aerostat.dm
=> [ЗЕРКАЛО] Mining bugfix

code/__spaceman_dmm.dm, vorestation.dme
=> [ЗЕРКАЛО] [MIRROR] moved sdmm defines to as early as possible in env [ABLE TO BE MERGED]

code/game/machinery/navbeacon.dm, code/game/machinery/pointdefense.dm, code/game/machinery/telecomms/logbrowser.dm, code/game/machinery/telecomms/machine_interactions.dm, code/game/machinery/telecomms/telemonitor.dm, code/game/machinery/telecomms/traffic_control.dm, code/game/objects/items/bodybag.dm, code/game/objects/items/devices/gps.dm, code/game/objects/items/devices/tvcamera.dm, code/game/objects/items/weapons/implants/implantcase.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/integrated_electronics/core/pins.dm, code/modules/integrated_electronics/core/tools.dm, code/modules/integrated_electronics/subtypes/input.dm, code/modules/integrated_electronics/subtypes/memory.dm, code/modules/mob/living/carbon/human/human_powers.dm, code/modules/overmap/ships/computers/helm.dm, code/modules/power/breaker_box.dm, code/modules/power/fusion/core/_core.dm, code/modules/power/fusion/fuel_assembly/fuel_control.dm, code/modules/power/fusion/fuel_assembly/fuel_injector.dm, code/modules/power/fusion/gyrotron/gyrotron.dm, code/modules/power/fusion/gyrotron/gyrotron_control.dm, code/modules/power/smes_construction.dm, code/modules/power/turbine.dm, code/modules/shuttles/shuttle_console.dm, code/modules/tgui/modules/overmap.dm
=> [ЗЕРКАЛО] Sanitization

vorestation.dme
=> [ЗЕРКАЛО] Back to SD

code/game/objects/items/contraband_vr.dm, code/game/objects/items/weapons/implants/implant_vr.dm, code/game/objects/structures/trash_pile_vr.dm, code/modules/economy/vending_machines_vr.dm
=> [ЗЕРКАЛО] Adds in 'compliance implant'

code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
=> [ЗЕРКАЛО] stops absorbed chimeras going feral

code/modules/admin/verbs/buildmode.dm
=> [ЗЕРКАЛО] Fixes build mode and makes it not terrible.

README.md
=> [ЗЕРКАЛО] README edit.

code/modules/reagents/reagents/drugs.dm, html/changelogs/cameron - drugfix.yml
=> [ЗЕРКАЛО] fixes psilocybin

code/game/objects/random/mapping.dm, maps/tether/tether-03-surface3.dmm
=> [ЗЕРКАЛО] Smole vending tweak

code/game/objects/items/crayons.dm
=> [ЗЕРКАЛО] we don't need to see your hate speech

code/modules/vore/eating/bellymodes_datum_vr.dm, code/modules/vore/eating/bellymodes_vr.dm
=> [ЗЕРКАЛО] Fixes sound and idle message issues with selective bellymode

code/modules/examine/descriptions/armor.dm
=> [ЗЕРКАЛО] tweaks armor descriptors

code/modules/mob/living/carbon/human/species/station/teshari.dm
=> [ЗЕРКАЛО] makes FBP teshari not overheat

code/game/machinery/cryopod.dm
=> [ЗЕРКАЛО] Proper Departures

code/game/objects/effects/mines.dm, code/game/objects/structures/cliff.dm, code/game/turfs/flooring/flooring_premade.dm, code/game/turfs/simulated/outdoors/snow.dm, code/game/turfs/simulated/water.dm, code/modules/mob/living/simple_mob/simple_mob.dm, code/modules/mob/living/simple_mob/subtypes/animal/sif/leech.dm, code/modules/vore/smoleworld/smoleworld_vr.dm
=> [ЗЕРКАЛО] ALL TERRAIN WINGS

code/modules/events/grid_check.dm, code/modules/power/generator.dm
=> [ЗЕРКАЛО] Gird check fixes

code/modules/busy_space_vr/organizations.dm
=> [ЗЕРКАЛО] minor typo fix

code/modules/mob/living/carbon/human/species/station/station_vr.dm
=> [ЗЕРКАЛО] Adjusts vulpkanin heat/cold handling. Makes them mid-way between human and taj.

code/modules/hydroponics/seed.dm, code/modules/mob/living/bot/bot.dm, code/modules/mob/living/bot/mulebot.dm
=> [ЗЕРКАЛО] [MIRROR] Spkrtn/fix/8703 8733 [ABLE TO BE MERGED]

code/modules/mob/living/simple_mob/subtypes/occult/unknown.dm, code/modules/nifsoft/software/15_misc.dm, code/modules/paperwork/faxmachine.dm, code/modules/paperwork/paper.dm, code/modules/research/designs/precursor.dm
=> [ЗЕРКАЛО] Allows ID to be inserted into fax machine by clicking it + 2 minor fixes

code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm, code/modules/vore/fluffstuff/custom_boxes_vr.dm
=> [ЗЕРКАЛО] Aku Zoles Briefcase fluff item

code/__defines/subsystems.dm, code/controllers/subsystems/overlays.dm, code/datums/datacore.dm, code/game/jobs/job/job.dm, code/game/objects/items/weapons/id cards/station_ids.dm, code/modules/admin/admin_verb_lists_vr.dm, code/modules/admin/verbs/debug.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/power/smes_vr.dm, code/modules/resleeving/designer.dm
=> [ЗЕРКАЛО] Upgrades OverlaySS. Fixes #3627

.github/workflows/ci.yml
=> [ЗЕРКАЛО] Bump yogstation13/DreamAnnotate from 1 to 2

code/game/machinery/rechargestation.dm
=> [ЗЕРКАЛО] Update rechargestation.dm

code/defines/obj/weapon.dm, code/game/objects/random/misc.dm
=> [ЗЕРКАЛО] Random-Soap Addon

code/modules/surgery/external_repair.dm
=> [ЗЕРКАЛО] Allows you to select if you want to heal brute or burn via surgery

code/modules/reagents/reagent_containers/syringes_vr.dm
=> [ЗЕРКАЛО] Fixes an oversight with syringes.

code/modules/mob/living/carbon/human/update_icons.dm
=> [ЗЕРКАЛО] Fixes taur loaf y offset

code/modules/surgery/encased.dm
=> [ЗЕРКАЛО] Changes names of a few surgery steps.

code/game/objects/random/guns_and_ammo.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes overlooked invisible spawner when mapping

code/modules/emotes/definitions/audible.dm
=> [ЗЕРКАЛО] Makes wing buzz use visible gender (his/her/their/hir/its)

code/game/objects/random/_random.dm
=> [ЗЕРКАЛО] [MIRROR] speculative fix for obj/random's not being deleted

code/modules/tgs/v5/chat_commands.dm
=> [ЗЕРКАЛО] Adds current map to status bot

code/game/objects/items/weapons/storage/belt.dm
=> [ЗЕРКАЛО] CE & Detective belts tweak

code/modules/recycling/disposal.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes a bug with deleted disposal outlets

code/modules/vore/fluffstuff/custom_clothes_vr.dm
=> [ЗЕРКАЛО] Fixes Freyr mask minor things

code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
=> [ЗЕРКАЛО] Fixes xenochimera uninjured check

config/alienwhitelist.txt
=> [ЗЕРКАЛО] Add some besk

code/modules/instruments/songs/play_legacy.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/vore/eating/living_vr.dm
=> [ЗЕРКАЛО] Fixes a few runtimes

code/modules/whitelist/whitelist.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes issue with language whitelists

maps/tether/tether-02-surface2.dmm
=> [ЗЕРКАЛО] Adds Snappy to Tether fish pond island

code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm, code/modules/vore/fluffstuff/custom_items_vr.dm
=> [ЗЕРКАЛО] fluff item spawns now

code/modules/mob/living/carbon/human/human.dm
=> [ЗЕРКАЛО] Makes not all masks obstruct gender

code/modules/emotes/emote_mob.dm
=> [ЗЕРКАЛО] Using asterisk reflects your message before returning

code/modules/mob/living/simple_mob/simple_mob_vr.dm
=> [ЗЕРКАЛО] Adds default belly fullscreen to all vore enabled simplemobs

code/_helpers/type2type.dm
=> [ЗЕРКАЛО] [MIRROR] fix || in type2parent switch, gentle refactor

code/game/gamemodes/events/holidays/Holidays.dm
=> [ЗЕРКАЛО] [MIRROR] Flavour Enhancement: Holidays

code/datums/supplypacks/hydroponics_vr.dm, code/game/objects/structures/crates_lockers/largecrate_vr.dm, code/modules/mob/living/simple_mob/subtypes/animal/pets/bird_vr.dm
=> [ЗЕРКАЛО] lets cargo order a pair of great tits

code/game/objects/items/weapons/storage/belt.dm
=> [ЗЕРКАЛО] [MIRROR] Adds flasks to the forensic belt allowed items

code/modules/mob/say_vr.dm, code/modules/vchat/css/ss13styles.css, code/stylesheet.dm
=> [ЗЕРКАЛО] Player Narrate

code/modules/mob/living/carbon/human/species/station/xenochimera_trait_vr.dm
=> [ЗЕРКАЛО] Fixes xenochimera flight not having restrictions

code/datums/components/material_container.dm
=> [ЗЕРКАЛО] Fixes inserting sheets with no defined material (like tiles) into machines

code/modules/error_handler/error_handler.dm, code/modules/error_handler/error_viewer.dm
Локализует code/modules/error_handler.
=> Локализация модуля Списка рантаймов

code/modules/mob/say_vr.dm, code/modules/nifsoft/software/13_soulcatcher.dm
=> [ЗЕРКАЛО] Various text-box QoL stuff

code/modules/mob/say_vr.dm
=> [ЗЕРКАЛО] Fixes two lobby bugs

code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human.dm
=> [ЗЕРКАЛО] On mob examine

tgui/yarn.lock
=> [ЗЕРКАЛО] Bump @xmldom/xmldom from 0.7.5 to 0.7.8 in /tgui

code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm
=> [ЗЕРКАЛО] Allergen Effect/Reaction Traits

maps/groundbase/groundbase_things.dm, maps/tether/tether_things.dm
=> [ЗЕРКАЛО] Blocks creation of shelter pods in the Fish Farm and Public Garden

code/_helpers/text.dm
=> [ЗЕРКАЛО] Permit (Some) Linebreaks

vorestation.dme
=> [ЗЕРКАЛО] Map swap

code/modules/mob/living/carbon/human/species/station/xenochimera_trait_vr.dm
=> [ЗЕРКАЛО] Xenochimera Fix for Numbing Fangs/Sharp Melee overriding Claws

code/modules/mob/living/carbon/human/emote.dm
=> [ЗЕРКАЛО] Makes some species specific emotes general

maps/offmap_vr/om_ships/lunaship.dm, maps/offmap_vr/om_ships/lunaship.dmm, vorestation.dme
=> [ЗЕРКАЛО] ISV LUNA - A Ship!

maps/stellar_delight/stellar_delight2.dmm
=> [ЗЕРКАЛО] Buffs paperwork on Stellar Delight (adds paperbin to captain's office, shredder to meeting room)

code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/examine_vr.dm, code/modules/mob/living/carbon/human/human.dm
=> [ЗЕРКАЛО] AR-Bs Employment Records

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/life.dm, code/modules/mob/living/living_defines.dm
=> [ЗЕРКАЛО] Fixes prommie glow

code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/prometheans.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm, code/modules/reagents/reagents/dispenser.dm
=> [ЗЕРКАЛО] Species Alcohol Mod Cleanup

code/modules/vore/eating/contaminate_vr.dm
=> [ЗЕРКАЛО] Makes contaminated boxes not fall apart

code/modules/hydroponics/trays/tray_tools.dm
=> [ЗЕРКАЛО] Makes hedge trimmers instakill vines

code/game/jobs/job/civilian_vr.dm
=> [ЗЕРКАЛО] Adds 'Rancher' alt title for botanist.

code/game/objects/effects/bump_teleporter.dm
=> [ЗЕРКАЛО] Fix bump teleporter

vorestation.dme
=> [ЗЕРКАЛО] Shhhh

code/modules/clothing/under/miscellaneous_vr.dm, code/modules/mob/living/carbon/human/inventory.dm
=> [ЗЕРКАЛО] equip_special

code/datums/supplypacks/misc_vr.dm
=> [ЗЕРКАЛО] Shortwave Headsets Crate

code/modules/busy_space_vr/air_traffic.dm
=> [ЗЕРКАЛО] Update air_traffic.dm

code/modules/materials/materials/metals/steel.dm, maps/offmap_vr/talon/talon_v2.dmm
=> [ЗЕРКАЛО] Fixes comfy chair recipies being removed by broken mirror

maps/offmap_vr/om_ships/lunaship.dmm
=> [ЗЕРКАЛО] ISV LUNA - Adjustments

code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm, code/modules/reagents/reactions/instant/instant_vr.dm
=> [ЗЕРКАЛО] removes meme reaction, adds sickness to regen

maps/stellar_delight/stellar_delight1.dmm, maps/stellar_delight/stellar_delight2.dmm, maps/stellar_delight/stellar_delight3.dmm
=> [ЗЕРКАЛО] Stellar Delight Upgrades NOV 2022

code/game/objects/structures/trash_pile_vr.dm, code/modules/clothing/under/miscellaneous_vr.dm
=> [ЗЕРКАЛО] Trash pile adjustments

code/modules/projectiles/guns/energy/laser.dm
=> [ЗЕРКАЛО] Makes the unmaintained antique behave like one

code/game/objects/items.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_blob.dm, code/modules/vore/fluffstuff/custom_clothes_vr.dm
=> [ЗЕРКАЛО] Adds ability for items to be whitelisted for protean blob-drop; adds that to Freyr's mask

tools/mapmerge2/requirements.txt
=> [ЗЕРКАЛО] Bump pillow from 9.0.1 to 9.3.0 in /tools/mapmerge2

tgui/packages/tgui-bench/package.json, tgui/yarn.lock
=> [ЗЕРКАЛО] Bump fastify from 3.29.0 to 3.29.4 in /tgui

code/modules/admin/admin_verbs_vr.dm
=> [ЗЕРКАЛО] Adjust Security Ticket

code/game/objects/items/weapons/storage/belt.dm
=> [ЗЕРКАЛО] Ticket printer in belt

maps/offmap_vr/om_ships/lunaship.dmm
=> [ЗЕРКАЛО] Update lunaship.dmm

code/modules/mob/living/silicon/robot/drone/drone_items.dm
=> [ЗЕРКАЛО] Adds Anesthetic Tanks to Medical Gripper

code/modules/mining/abandonedcrates.dm, code/modules/mining/abandonedcrates_vr.dm
=> [ЗЕРКАЛО] Makes lootboxes a hell of a lot more random

.github/workflows/autochangelog.yml, .github/workflows/ci.yml, .github/workflows/render_nanomaps.yml
=> [ЗЕРКАЛО] Switches workflows to use Ubuntu 20.04

code/game/magic/archived_book.dm, code/modules/admin/admin_verb_lists_vr.dm, code/modules/admin/admin_verbs_vr.dm, code/modules/library/lib_machines.dm, maps/groundbase/gb-centcomm.dmm, maps/stellar_delight/ship_centcom.dmm, maps/tether/submaps/tether_centcom.dmm
=> [ЗЕРКАЛО] Buffs library book management

code/datums/components/material_container.dm
=> [ЗЕРКАЛО] Fixes autolathe thing.

code/modules/mob/living/living.dm
=> [ЗЕРКАЛО] [MIRROR] rejuvenate strips ghost vision from mobs

code/modules/mob/living/carbon/brain/MMI.dm
=> [ЗЕРКАЛО] Fixes MMIs to restore vision

code/game/objects/items/poi_items.dm, code/game/objects/items/weapons/manuals.dm, code/game/objects/structures/props/blackbox.dm, code/modules/projectiles/guns/projectile/automatic_vr.dm
=> [ЗЕРКАЛО] Fixes time travel (Lore adjustment for POI loot)

maps/groundbase/westwilds/westwilds1.dmm, maps/groundbase/westwilds/westwilds2.dmm
=> [ЗЕРКАЛО] QoL changes to xenoarch

code/modules/food/food.dm, code/modules/food/kitchen/cooking_machines/_appliance.dm
=> [ЗЕРКАЛО] [MIRROR] Naming Food & Blood Cakes

code/modules/clothing/suits/miscellaneous_vr.dm
=> [ЗЕРКАЛО] Fixes wrong item being species restricted

maps/groundbase/gb-z1.dmm, maps/groundbase/gb-z2.dmm, maps/groundbase/gb-z3.dmm
=> [ЗЕРКАЛО] Adds more nanomeds to gb

_build_dependencies.sh
=> [ЗЕРКАЛО] [MIRROR] match server byond version for CI

code/modules/mob/living/carbon/human/species/station/station_vr.dm
=> [ЗЕРКАЛО] Updated ingame Unathi lroe

code/game/machinery/atm_ret_field.dm
=> [ЗЕРКАЛО] Fixes #14118

code/modules/client/preference_setup/loadout/loadout_uniform.dm
=> [ЗЕРКАЛО] Removes job requirement from Bartender Skirt

code/modules/mob/living/silicon/ai/ai_remote_control.dm
=> [ЗЕРКАЛО] Fixes #14124

code/modules/vehicles/rover_vr.dm, vorestation.dme
=> [ЗЕРКАЛО] Re-enables old rover

code/modules/tgui/tgui.dm, code/modules/tgui/tgui_window.dm, tgui/global.d.ts, tgui/public/tgui.html
=> [ЗЕРКАЛО] Adds tgui strict mode

code/game/objects/items/weapons/material/shards.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes shards having unlimited afterattack range

code/game/objects/items/devices/hacktool.dm
=> [ЗЕРКАЛО] Simplified Hacktool

code/game/machinery/doors/airlock.dm, code/game/objects/items/devices/hacktool.dm
=> [ЗЕРКАЛО] Further Hacktool Adjustments

code/game/objects/effects/decals/remains.dm
=> [ЗЕРКАЛО] [MIRROR] Cleanable robo remains

code/modules/mob/living/carbon/human/species/species_vr.dm, code/modules/mob/living/carbon/human/update_icons.dm
=> [ЗЕРКАЛО] Fixes "Revert "promethean fixes and QoLs""

code/modules/mob/living/carbon/human/species/station/alraune.dm, code/modules/mob/living/carbon/human/species/station/blank_vr.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm, code/modules/mob/living/carbon/human/species/station/station_special_vr.dm, code/modules/mob/living/carbon/human/species/station/station_vr.dm
=> [ЗЕРКАЛО] Makes languages properly preview on species preview window

code/modules/lore_codex/lore_data_vr/main.dm, code/modules/lore_codex/lore_data_vr/species.dm
=> [ЗЕРКАЛО] Updates Traveller's Guide with new species lore

code/modules/lore_codex/lore_data_vr/history.dm, code/modules/lore_codex/lore_data_vr/main.dm, code/modules/lore_codex/lore_data_vr/species.dm, vorestation.dme
=> [ЗЕРКАЛО] Adds "History" section to Traveller's Guide

code/game/objects/items/weapons/capture_crystal.dm, code/modules/lore_codex/codex_tree.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
=> [ЗЕРКАЛО] Some runtime fixes + oldchat icons

maps/tether/tether-01-surface1.dmm
=> [ЗЕРКАЛО] Fixes stray newscaster

code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/prometheans.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/station_vr.dm
=> [ЗЕРКАЛО] Gives prometheans their language as inheirent, removes Tavan from Altevians

code/modules/admin/verbs/smite_vr.dm, code/modules/mob/living/silicon/robot/emote.dm
=> [ЗЕРКАЛО] Gives borgs access to human emotes

config/alienwhitelist.txt
=> [ЗЕРКАЛО] Whitelist update

code/modules/paperwork/folders.dm, code/modules/reagents/hoses/connector.dm, code/modules/reagents/machinery/dispenser/reagent_tank.dm, maps/stellar_delight/stellar_delight2.dmm
=> [ЗЕРКАЛО] A few fixes

code/game/objects/items/devices/ticket_printer.dm, code/modules/paperwork/folders.dm
=> [ЗЕРКАЛО] ticket printers and folders are now holsterable

code/modules/client/preference_setup/general/03_body.dm, code/modules/mob/living/carbon/human/human_defines_vr.dm, code/modules/mob/living/carbon/human/human_helpers_vr.dm, code/modules/tgui/modules/appearance_changer.dm, tgui/packages/tgui/interfaces/AppearanceChanger.js
=> [ЗЕРКАЛО] creates a tab in the TF menu for changing markings

code/game/jobs/job_controller.dm
=> [ЗЕРКАЛО] Allows suit, mask and head slot items in loadout to override job items

code/modules/mob/living/carbon/human/ai_controlled/ai_controlled_vr.dm, vorestation.dme
=> [ЗЕРКАЛО] stops ai controlled humanoids from spawning with sensors on

code/modules/reagents/reagent_containers/borghypo.dm
=> [ЗЕРКАЛО] Gives service borgs some cream

maps/groundbase/gb-z1.dmm
=> [ЗЕРКАЛО] Adds a shovel to RP engineering's misc tool closet.

code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
=> [ЗЕРКАЛО] Makes aquatic noms respect drop prefs

maps/groundbase/gb-z2.dmm, maps/groundbase/gb-z3.dmm, maps/groundbase/westwilds/westwilds1.dmm, maps/groundbase/westwilds/westwilds2.dmm
=> [ЗЕРКАЛО] Map tweaks

code/datums/outfits/outfit.dm, code/game/objects/items.dm, code/game/objects/items/weapons/tape.dm, code/modules/mob/inventory.dm
=> [ЗЕРКАЛО] Fixes critical inventory equipment bug

maps/groundbase/gb-z1.dmm, maps/tether/tether-03-surface3.dmm
=> [ЗЕРКАЛО] Adds some New Year cheer

code/game/machinery/portable_turret.dm, code/modules/blob2/overmind/powers.dm
=> [ЗЕРКАЛО] Fixes turret mecha targeting

code/game/objects/items/weapons/cosmetics.dm, code/modules/resleeving/autoresleever.dm
=> [ЗЕРКАЛО] Fixes a pair of runtimes

code/datums/supplypacks/misc_vr.dm, code/datums/supplypacks/munitions_vr.dm, code/datums/supplypacks/supply.dm, code/datums/supplypacks/voidsuits_vr.dm, code/game/jobs/access_datum_vr.dm, code/game/machinery/suit_storage_unit_vr.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/structures/crates_lockers/closets/misc_vr.dm, maps/groundbase/gb-z3.dmm, maps/groundbase/groundbase_telecomms.dm, maps/offmap_vr/talon/talon_v2.dmm, maps/stellar_delight/stellar_delight1.dmm, maps/stellar_delight/stellar_delight_telecomms.dm, maps/submaps/admin_use_vr/ert.dmm, maps/tether/tether_telecomms.dm
=> [ЗЕРКАЛО] Fixes some Oversights

maps/groundbase/gb-z3.dmm, maps/groundbase/westwilds/westwilds1.dmm, maps/groundbase/westwilds/westwilds2.dmm
=> [ЗЕРКАЛО] Smole map tweaks

code/modules/clothing/spacesuits/miscellaneous.dm
=> [ЗЕРКАЛО] [MIRROR] grammar standardization for softsuits

code/modules/vore/eating/belly_obj_vr.dm
=> [ЗЕРКАЛО] Makes IDs not contaminate in non-contaminating bellies

code/modules/vore/fluffstuff/custom_clothes_vr.dm
=> [ЗЕРКАЛО] Minor typo correction

maps/groundbase/gb-z1.dmm, maps/stellar_delight/stellar_delight1.dmm, maps/tether/tether-05-station1.dmm
=> [ЗЕРКАЛО] map edits

code/game/objects/items/weapons/gift_wrappaper.dm, code/game/objects/items/weapons/tools/crowbar.dm, code/game/objects/items/weapons/tools/screwdriver.dm, code/game/objects/items/weapons/tools/wirecutters.dm, code/game/objects/items/weapons/tools/wrench.dm, code/modules/assembly/signaler.dm, code/modules/economy/coins.dm, code/modules/mob/living/living_defense.dm, code/modules/power/cells/device_cells_vr.dm, maps/expedition_vr/aerostat/_aerostat_science_outpost.dm
=> [ЗЕРКАЛО] Various minor fixes

code/modules/research/designs/medical.dm
=> [ЗЕРКАЛО] Makes advanced health analyzers creatable via R&D

code/datums/components/material_container.dm, code/game/machinery/autolathe.dm, code/game/objects/items/stacks/stack.dm, code/modules/food/kitchen/smartfridge/smartfridge.dm, code/modules/materials/materials/glass.dm, code/modules/materials/materials/glass_vr.dm, code/modules/materials/materials/metals/hull.dm, code/modules/materials/materials/metals/hull_vr.dm, code/modules/materials/materials/metals/metals.dm, code/modules/materials/materials/metals/plasteel.dm, code/modules/materials/materials/metals/plasteel_vr.dm, maps/tether/tether-03-surface3.dmm
=> [ЗЕРКАЛО] Fixes autolathe, material and smartfridge issues

code/game/objects/structures/ghost_pods/event_vr.dm
=> [ЗЕРКАЛО] Maint pred cancel tweak

code/game/jobs/job/captain_vr.dm, code/game/jobs/job/engineering_vr.dm, code/game/jobs/job/security_vr.dm, maps/stellar_delight/stellar_delight_jobs.dm
=> [ЗЕРКАЛО] Allows SD-exclusive job titles to be used anywhere

code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/game/objects/structures/stool_bed_chair_nest/chairs_vr.dm, code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
=> [ЗЕРКАЛО] Fixes comfy chair colors

code/modules/planet/virgo4_vr.dm
=> [ЗЕРКАЛО] Makes Virgo 4 extreme weathers dissipate

code/game/objects/items/trash_vr.dm, code/game/objects/structures/door_assembly.dm, code/game/objects/structures/windoor_assembly.dm, code/modules/emotes/definitions/synthetics.dm, code/modules/events/event_container.dm, code/modules/events/event_container_vr.dm, code/modules/events/event_dynamic.dm, code/modules/mob/living/silicon/robot/robot_modules/station.dm, code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm, maps/groundbase/groundbase_events.dm, maps/stellar_delight/stellar_delight_events.dm, maps/tether/tether_events.dm, vorestation.dme
=> [ЗЕРКАЛО] Adjusts events and refactors borgs a bit in process

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm
=> [ЗЕРКАЛО] Some OCD fixes to tether's medical floor markings and firelocks

code/game/objects/items.dm, code/modules/admin/admin.dm
=> [ЗЕРКАЛО] Fixes two admin bugs

code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
=> [ЗЕРКАЛО] Fixes sidona's robes not being selectable properly

code/modules/fishing/fishing_rod.dm
=> [ЗЕРКАЛО] un-nerfs fishing from previous change

maps/stellar_delight/stellar_delight1.dmm
=> [ЗЕРКАЛО] SD Edits!

code/_helpers/global_lists_vr.dm, code/game/objects/effects/semirandom_mobs_vr.dm, code/game/turfs/flooring/seasonal.dm, code/modules/mining/abandonedcrates_vr.dm, code/modules/planet/virgo3c_vr.dm, code/modules/vore/mouseray.dm, code/modules/xenoarcheaology/artifacts/replicator_vr.dm, maps/expedition_vr/beach/_beach.dm, maps/stellar_delight/stellar_delight2.dmm, maps/tether/tether_things.dm
=> [ЗЕРКАЛО] Zorren win!

code/game/objects/structures/crates_lockers/closets/secure/personal.dm
=> [ЗЕРКАЛО] Fixes personal lockers robbing borgs of their modules

code/modules/client/preference_setup/loadout/loadout_suit_vr.dm
=> [ЗЕРКАЛО] fixes "hoodie with hood" loadout option

code/modules/mob/new_player/sprite_accessories_extra.dm
=> [ЗЕРКАЛО] Extremely quick marking fix

code/game/turfs/flooring/seasonal.dm, maps/groundbase/eastwilds/eastwilds template.dmm, maps/groundbase/eastwilds/eastwilds1.dmm, maps/groundbase/eastwilds/eastwilds2.dmm, maps/groundbase/gb-z1.dmm, maps/groundbase/gb-z2.dmm, maps/groundbase/gb-z3.dmm, maps/groundbase/northwilds/northwilds template.dmm, maps/groundbase/northwilds/northwilds1.dmm, maps/groundbase/northwilds/northwilds2.dmm, maps/groundbase/pois/outdoors8.dmm, maps/groundbase/pois/template.dmm, maps/groundbase/southwilds/southwilds template.dmm, maps/groundbase/southwilds/southwilds1.dmm, maps/groundbase/southwilds/southwilds2.dmm, maps/groundbase/southwilds/southwilds3.dmm, maps/groundbase/southwilds/villagepois/long1.dmm, maps/groundbase/southwilds/villagepois/long3.dmm, maps/groundbase/southwilds/villagepois/square10.dmm, maps/groundbase/southwilds/villagepois/wide2.dmm, maps/groundbase/southwilds/villagepois/wide6.dmm, maps/groundbase/westwilds/westwilds template.dmm, maps/groundbase/westwilds/westwilds1.dmm, maps/groundbase/westwilds/westwilds2.dmm
=> [ЗЕРКАЛО] fixes RP seasonal subtypes and adds seasonal water

code/modules/organs/robolimbs_vr.dm
=> [ЗЕРКАЛО] Update whitelist on robolimbs_vr.dm

code/modules/events/roaming_wildlife.dm
=> [ЗЕРКАЛО] Removes aquatic spawns from wildlife event for now

maps/groundbase/gb-mining.dmm
=> [ЗЕРКАЛО] Fixes RP mining's edge

code/modules/mob/living/silicon/robot/dogborg/dog_sleeper_vr.dm, code/modules/mob/living/silicon/robot/robot_vr.dm
=> [ЗЕРКАЛО] adds a button for ingesting dogborg sleeper contents + couple other miscellaneous slightly related fixes

maps/groundbase/gb-z3.dmm
=> [ЗЕРКАЛО] Fixes landmarks on 3c

code/datums/uplink/tools_vr.dm, code/game/objects/items/weapons/storage/pouches.dm
=> [ЗЕРКАЛО] Uplink and Pouch Tweaks

code/modules/admin/verbs/randomverbs.dm
=> [ЗЕРКАЛО] Adds new admin character spawn method

code/game/mecha/mecha.dm
=> [ЗЕРКАЛО] [MIRROR] Blobs do damage to mechs

code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm
=> [ЗЕРКАЛО] Add the fennec crown to the fluff items list

code/modules/organs/organ_icon.dm
=> [ЗЕРКАЛО] Potential "override fail" fix

code/game/objects/effects/decals/Cleanable/misc.dm, code/modules/persistence/effects/filth.dm, code/modules/persistence/effects/filth_vr.dm, code/modules/persistence/effects/trash.dm, vorestation.dme
=> [ЗЕРКАЛО] better persistent dirt

code/modules/client/preference_setup/vore/07_traits.dm, code/modules/mob/living/carbon/human/human_defines_vr.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_powers.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm, code/modules/organs/robolimbs_custom.dm
=> [ЗЕРКАЛО] few small fixes and improvements for proteans

code/modules/resleeving/designer.dm
=> [ЗЕРКАЛО] fixes an issue with promethean resleeving and allows bodytype changing in records

code/modules/mob/say_vr.dm
=> [ЗЕРКАЛО] This should fix dialogue log spam with player narrate

code/datums/mind_vr.dm, code/modules/client/verbs/character_directory.dm, tgui/packages/tgui/interfaces/CharacterDirectory.js
=> [ЗЕРКАЛО] adds the ability to use mind-based character directories

maps/groundbase/gb-z1.dmm, maps/groundbase/westwilds/westwilds2.dmm, maps/tether/tether-01-surface1.dmm, maps/tether/tether-03-surface3.dmm
=> [ЗЕРКАЛО] Minor map fixes

code/modules/client/preference_setup/loadout/loadout_accessories.dm
=> [ЗЕРКАЛО] Minor spelling mistake

code/modules/vore/persist/persist_vr.dm
=> [ЗЕРКАЛО] fixes unprioritised markings during persisitence

code/game/objects/structures/fitness_vr.dm, maps/groundbase/gb-misc.dmm, maps/stellar_delight/ship_misc.dmm, maps/tether/submaps/tether_misc.dmm
=> [ЗЕРКАЛО] Fixes boxing ropes (bottom) and boxing turnbuckle not blocking properly

config/jukebox.json
=> [ЗЕРКАЛО] Removes one comma

code/modules/fireworks/firework_launcher.dm
=> [ЗЕРКАЛО] Fixes #14331

code/modules/mining/drilling/drill.dm
=> [ЗЕРКАЛО] Fixes #14268

code/modules/assembly/timer.dm
=> [ЗЕРКАЛО] Fixes #13730

code/modules/mob/language/language.dm, code/modules/mob/language/snowflake.dm, code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/station_vr.dm, code/modules/mob/living/simple_mob/subtypes/vore/dominated_brain.dm, code/modules/mob/living/simple_mob/subtypes/vore/shadekin/shadekin.dm, vorestation.dme
=> [ЗЕРКАЛО] Buff Shadekin Empathy (And other hive languages)

code/game/dna/dna2.dm, code/game/dna/dna2_helpers.dm, code/modules/client/preference_setup/vore/07_traits.dm, code/modules/mob/living/carbon/human/species/species_getters.dm, code/modules/mob/living/living_defines_vr.dm
=> [ЗЕРКАЛО] Adds ability to customize discomfort

code/modules/xenobio/items/slimepotions.dm
=> [ЗЕРКАЛО] Fixes slime docility potion being reusable

code/modules/client/preference_setup/vore/07_traits.dm
=> [ЗЕРКАЛО] sanitizes selection of custom bases in prefs

code/game/atoms.dm, code/modules/mob/living/simple_mob/subtypes/animal/animal.dm
=> [ЗЕРКАЛО] [MIRROR] Simple animal flavour text will now show instead of desc, if set.

code/modules/client/preference_setup/vore/09_misc.dm
=> [ЗЕРКАЛО] Hitting cancel when setting character ad no longer blanks it in setup

code/modules/events/roaming_wildlife.dm, maps/groundbase/groundbase_events.dm
=> [ЗЕРКАЛО] Adjustments to wildlife event

code/game/objects/structures/janicart.dm
=> [ЗЕРКАЛО] Fixes #14409

maps/groundbase/gb-z1.dmm, maps/groundbase/gb-z2.dmm
=> [ЗЕРКАЛО] RP Edits

code/game/objects/items/devices/advnifrepair.dm
=> [ЗЕРКАЛО] Fixes NIF repair tool using up nanopaste when full

code/modules/client/preference_setup/loadout/loadout_utility.dm
=> [ЗЕРКАЛО] Adds Lanterns to Loadout Selection

code/modules/food/food/snacks.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm, code/modules/vore/eating/living_vr.dm
=> [ЗЕРКАЛО] Adds Food Stuffer trait

code/game/mecha/combat/combat.dm, code/game/mecha/combat/durand.dm, code/game/mecha/combat/gorilla.dm, code/game/mecha/combat/gygax.dm, code/game/mecha/combat/marauder.dm, code/game/mecha/combat/phazon.dm, code/game/mecha/mecha.dm, code/game/mecha/micro/micro.dm, code/game/mecha/micro/security.dm, code/game/mecha/micro/utility.dm, code/game/mecha/working/ripley.dm, code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/mecha.dm
=> [ЗЕРКАЛО] [MIRROR] Removes unused mecha damage absorbtion list.

code/__defines/mobs.dm, code/modules/client/preference_setup/general/03_body.dm
=> [ЗЕРКАЛО] [MIRROR] fixes robo limbs setting child limbs afterwards

code/game/objects/items/weapons/circuitboards/circuitboards_vr.dm
=> [ЗЕРКАЛО] Add required components to circuit board examine text

code/game/objects/items/weapons/clown_items.dm, code/game/objects/structures/watercloset.dm, code/modules/reagents/reagents/other.dm
=> [ЗЕРКАЛО] [MIRROR] allows soap and showers to clean toes, and space cleaner to actually clean synthetic toes

code/modules/admin/fix_player_notes_listing.dm
=> [ЗЕРКАЛО] [MIRROR] Adds a proc to fix player notes listings

code/modules/emotes/definitions/audible_furry_vr.dm
=> [ЗЕРКАЛО] Small typing fix

code/modules/emotes/definitions/visible.dm
=> [ЗЕРКАЛО] Fixes mobs falling asleep when fainting

code/modules/client/preference_setup/loadout/loadout_uniform_vr.dm
=> [ЗЕРКАЛО] Fixes "Colored Feminine Jumpsuit"

code/controllers/master.dm
=> [ЗЕРКАЛО] [MIRROR] Ported LemonInTheDark's scheduler offset optimization.

code/controllers/subsystems/xenoarch.dm, code/modules/emotes/definitions/audible_scream_vr.dm, code/modules/food/food/snacks.dm, code/modules/mob/living/carbon/human/species/species_getters.dm
=> [ЗЕРКАЛО] Some runtime fixes

code/modules/client/preference_setup/general/03_body.dm
=> [ЗЕРКАЛО] [MIRROR] Child organs can't robotize() if they're already robotic

code/modules/client/preference_setup/general/03_body.dm
=> [ЗЕРКАЛО] fixes nanoform limbs specifically from changing their child limbs

code/modules/admin/topic.dm
=> [ЗЕРКАЛО] Admin href fax topic thing fix

code/modules/admin/verbs/adminsay.dm
=> [ЗЕРКАЛО] Removes R_STEALTH perm requirement for staff chats

code/modules/client/preference_setup/vore/07_traits.dm
=> [ЗЕРКАЛО] proper sanitization of cold and heat messages

code/modules/food/food/snacks.dm
=> [ЗЕРКАЛО] Makes muffins not have beans in them

config/jukebox.json
=> [ЗЕРКАЛО] jukebox

code/modules/player_tips_vr/player_tips_list_vr.dm
=> [ЗЕРКАЛО] Changes VORESTation to Vorestation in player_tips_list

code/modules/mob/living/simple_mob/subtypes/animal/alien animals/succlet.dm, config/jukebox.json
=> [ЗЕРКАЛО] Succlet adjust

code/modules/player_tips_vr/player_tips_controller_vr.dm
=> [ЗЕРКАЛО] Fixes player tips becoming spammy past 75 minutes

code/modules/client/preference_setup/general/03_body.dm
=> [ЗЕРКАЛО] fix default proteans being technically organic shift start

code/__defines/mobs.dm, code/game/jobs/job/job.dm
=> [ЗЕРКАЛО] Broke

code/game/turfs/flooring/seasonal.dm
=> [ЗЕРКАЛО] bees and things

code/modules/admin/DB ban/functions.dm
=> [ЗЕРКАЛО] Adds Href Token to database banning forms

code/modules/mob/living/carbon/human/say.dm
=> [ЗЕРКАЛО] fixes muting not muting

code/modules/client/preferences_vr.dm
=> [ЗЕРКАЛО] makes player tips verb save

code/modules/vore/resizing/resize_vr.dm
=> [ЗЕРКАЛО] fixes a problem with my stepping code

code/game/objects/items.dm, code/game/objects/structures/crates_lockers/__closets.dm, code/game/objects/structures/simple_doors.dm, code/game/turfs/simulated/outdoors/survival_action_vr.dm, code/modules/ai/ai_holder_targeting.dm, code/modules/emotes/definitions/audible_furry_vr.dm, code/modules/emotes/definitions/audible_snap.dm, code/modules/lighting/lighting_fake_sun_vr.dm, code/modules/mob/living/living.dm, code/modules/mob/living/silicon/emote.dm, code/modules/multiz/movement.dm, code/modules/vore/eating/living_vr.dm
=> [ЗЕРКАЛО] Misc fixes

code/modules/client/preference_setup/vore/08_nif.dm
=> [ЗЕРКАЛО] no free nifs from switching species from protean

maps/tether/submaps/tether_centcom.dmm
=> [ЗЕРКАЛО] Hopefully fixes longstanding tether active edge

code/modules/client/preferences.dm
=> [ЗЕРКАЛО] sets the default selection in slot select menu to current char

code/modules/mob/holder.dm, code/modules/vore/resizing/holder_vr.dm, vorestation.dme
=> [ЗЕРКАЛО] fixes a few things with holder objects

code/modules/player_tips_vr/player_tips_controller_vr.dm
=> [ЗЕРКАЛО] Makes player tips track CKeys to inform how to turn them off.

code/game/objects/items/weapons/capture_crystal.dm
=> [ЗЕРКАЛО] cap crystal ooc escape fix

code/_helpers/icons.dm
=> [ЗЕРКАЛО] [MIRROR] Fix AI hologram sprites.

code/modules/player_tips_vr/player_tips_controller_vr.dm
=> [ЗЕРКАЛО] Fixes runtime from mobs without minds

code/_helpers/unsorted.dm
=> [ЗЕРКАЛО] [MIRROR] Adds const to holodeck copy bypass list.

code/modules/vore/eating/vorepanel_vr.dm
=> [ЗЕРКАЛО] makes Process belly button call death() on target

code/modules/food/food/z_custom_food_vr.dm, code/modules/shieldgen/directional_shield.dm
=> [ЗЕРКАЛО] Fixes 2 runtimes

code/modules/vore/resizing/holder_vr.dm
=> [ЗЕРКАЛО] fix for mob holders disappearing on pickup from inventory

maps/submaps/surface_submaps/mountains/mountains.dm, maps/submaps/surface_submaps/wilderness/wilderness.dm
=> [ЗЕРКАЛО] [MIRROR] Removes BluSD and DJOutpost4 from spawning

code/modules/client/preference_setup/global/setting_datums.dm, code/modules/client/preferences_vr.dm, code/modules/organs/pain.dm
=> [ЗЕРКАЛО] Makes cooldown between pain messages a pre-set global preference

code/modules/client/preference_setup/loadout/loadout_suit_vr.dm
=> [ЗЕРКАЛО] adds the bladerunner coat to loadout

code/game/objects/items/paintkit.dm
=> [ЗЕРКАЛО] [MIRROR] Suit kits no longer set item_state on hooded clothes

code/modules/mob/living/living_defense.dm
=> [ЗЕРКАЛО] [MIRROR] Lava Damage Adjustment

code/game/turfs/flooring/flooring_premade.dm, maps/expedition_vr/space/_debrisfield.dm, maps/submaps/pois_vr/debris_field/_templates.dm, maps/submaps/pois_vr/debris_field/debrisfield_things.dm, maps/submaps/pois_vr/debris_field/ship_tourist_overrun.dmm
=> [ЗЕРКАЛО] Adds a new POI for debris field with a new ghostpod type

code/modules/client/preference_setup/vore/02_size.dm, code/modules/mob/living/carbon/human/species/species_shapeshift_vr.dm, code/modules/mob/say_vr.dm
=> [ЗЕРКАЛО] Allows speech bubbles to be selected in char setup and saved

code/modules/mining/machinery/machine_processing.dm
=> [ЗЕРКАЛО] Allows ore processors to start collecting ore pieces again

code/modules/client/preference_setup/vore/02_size.dm
=> [ЗЕРКАЛО] Enables Testing Character Voices in Setup

config/alienwhitelist.txt
=> [ЗЕРКАЛО] Adds an alien

code/modules/mob/living/simple_mob/subtypes/mechanical/drones/mining_drone.dm, code/modules/projectiles/projectile/energy.dm
=> [ЗЕРКАЛО] Makes mining drones have a smarter IFF

config/alienwhitelist.txt
Reverts BastionOfEndeavor/BastionOfEndeavor2#591
=> Revert "[ЗЕРКАЛО] Adds an alien"

code/modules/xenobio/items/slimepotions_vr.dm
=> [ЗЕРКАЛО] fixes a small typo on the slime fertility agent

code/modules/mob/living/carbon/brain/brain.dm, code/modules/mob/mob_defines.dm, code/modules/mob/typing_indicator.dm
=> [ЗЕРКАЛО] Hopefully fixes stuck typing indicators when changing bubble mid-typing

code/controllers/subsystems/ticker.dm, code/modules/client/preference_setup/vore/09_misc.dm, code/modules/client/preferences_vr.dm, code/modules/mob/new_player/new_player.dm
=> [ЗЕРКАЛО] Start With Backup Implant setting

code/game/objects/random/mob_vr.dm, maps/groundbase/groundbase_poi_stuff.dm, maps/groundbase/pois/outdoors16.dmm
=> [ЗЕРКАЛО] Adds new POI to RP, creates scug spawner object

code/datums/mind.dm, code/datums/mind_vr.dm, code/game/antagonist/antagonist_print.dm, code/game/gamemodes/objective.dm, code/modules/vore/eating/belly_obj_vr.dm
=> [ЗЕРКАЛО] Adds 'vore' objective

code/__defines/admin.dm, code/game/objects/items/devices/transfer_valve.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/pray.dm, code/modules/client/verbs/who.dm, code/modules/power/singularity/particle_accelerator/particle_control.dm
=> [ЗЕРКАЛО] more fixed admin hrefs

code/modules/xenoarcheaology/effects/cellcharge.dm
=> [ЗЕРКАЛО] stops robots from getting spammed on different z levels from cellcharge anomaly

code/modules/mob/living/carbon/human/emote.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes an oversight with default emote retrieval.

code/modules/projectiles/projectile.dm
=> [ЗЕРКАЛО] [MIRROR] Projectiles properly set starting var.

SpacemanDMM.toml, code/ATMOSPHERICS/components/valve.dm, code/game/machinery/syndicatebeacon.dm, code/modules/flufftext/TextFilters.dm, code/modules/mob/living/silicon/robot/subtypes/lost_drone_vr.dm, code/modules/mob/mob_helpers.dm, code/modules/power/singularity/singularity.dm, code/unit_tests/zas_tests.dm
=> [ЗЕРКАЛО] Resolves SDMM warnings

code/modules/client/preference_setup/general/03_body.dm, code/modules/mob/new_player/preferences_setup.dm
=> [ЗЕРКАЛО] [MIRROR] allows animations to be toggled in preferences

code/modules/nifsoft/nif.dm
=> [ЗЕРКАЛО] NIF damage minitweak

maps/submaps/pois_vr/debris_field/debrisfield_things.dm, maps/submaps/pois_vr/debris_field/ship_tourist_overrun.dmm
=> [ЗЕРКАЛО] Fixes window icons on luxury yacht, nerfs royal spider eggs

code/modules/admin/verbs/adminhelp.dm, code/modules/admin/verbs/adminpm.dm, code/modules/admin/verbs/adminsay.dm, code/modules/client/preference_setup/vore/02_size.dm
=> [ЗЕРКАЛО] Fixes some admin perms not being properly checked

code/modules/mob/living/simple_mob/simple_mob.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes Simplemob Movement Delay

code/modules/food/drinkingglass/mugs.dm
=> [ЗЕРКАЛО] [MIRROR] Fix some coffee mugs not using the correct sprites

code/modules/mob/living/carbon/human/species/station/prometheans.dm
=> [ЗЕРКАЛО] [MIRROR] Prometheans self clean adjust.

code/game/objects/items/weapons/storage/mre.dm, code/modules/admin/admin.dm
=> [ЗЕРКАЛО] Two fix

code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm
=> [ЗЕРКАЛО] Changelog Reroute

code/game/objects/items.dm, code/game/objects/items/weapons/material/twohanded.dm, code/game/objects/items/weapons/melee/energy.dm, code/game/objects/weapons.dm, code/modules/examine/descriptions/guns.dm, code/modules/examine/descriptions/items.dm, code/modules/examine/descriptions/weapons.dm, code/modules/projectiles/guns/energy/gunsword_vr.dm, vorestation.dme
=> [ЗЕРКАЛО] Weapon Info on Examine

code/datums/looping_sounds/_looping_sound.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes a looping sound bug, adds additional options

code/modules/client/preference_setup/general/01_basic.dm, code/modules/client/preference_setup/general/05_background.dm, code/modules/client/preference_setup/general/06_flavor.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/living_vr.dm, code/modules/mob/living/silicon/silicon.dm
=> [ЗЕРКАЛО] Relaxes Sanitization

code/game/turfs/simulated/floor_attackby.dm
=> [ЗЕРКАЛО] Allows quickreplace of flooring types that use nonstandard plating

code/datums/supplypacks/atmospherics.dm, code/modules/mob/living/silicon/robot/robot_modules/station.dm
=> [ЗЕРКАЛО] [MIRROR] Finally allows RPD to be used.

code/game/objects/items/weapons/storage/mre.dm
=> [ЗЕРКАЛО] [MIRROR] Fixes a raunchy typo

code/modules/emotes/definitions/synthetics.dm, code/modules/mob/living/silicon/emote.dm, code/modules/mob/living/silicon/robot/emote.dm
=> [ЗЕРКАЛО] [MIRROR] *bing

code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
=> [ЗЕРКАЛО] [MIRROR] Siege Hivebots Use Proper Projectile

code/_onclick/click.dm
=> [ЗЕРКАЛО] [MIRROR] Click catchers no longer display as Darkness

code/modules/reagents/machinery/injector_maker.dm
=> [ЗЕРКАЛО] fixes small injectors not working from printer

code/game/machinery/hologram.dm, code/modules/mob/living/silicon/ai/ai.dm
=> [ЗЕРКАЛО] [MIRROR] AI can change their hologram color.

code/modules/mob/living/carbon/human/human_movement.dm
=> [ЗЕРКАЛО] Fixes some minor issues with water/snow slowdown

code/modules/clothing/under/miscellaneous.dm
=> [ЗЕРКАЛО] Clothing Coverage Tweaks

code/game/mecha/equipment/weapons/energy/laser.dm, code/modules/research/mechfab_designs_vr.dm
=> [ЗЕРКАЛО] Adds a new mech weapon, the GA-X Experimental Gamma Laser

maps/submaps/pois_vr/debris_field/mining_drones.dmm
=> [ЗЕРКАЛО] Replaces mining drones with salvage drones. Splits them up

code/_onclick/hud/hud.dm
=> [ЗЕРКАЛО] [MIRROR] fixes a runtime in huds deleting and the gun deletion on login issue

maps/tether/tether-05-station1.dmm
=> [ЗЕРКАЛО] Fixes missing pipes on tether.

tgui/package.json, tgui/yarn.lock
=> [ЗЕРКАЛО] Bump webpack from 5.73.0 to 5.76.0 in /tgui

code/game/machinery/computer/guestpass.dm
=> [ЗЕРКАЛО] Fixes some bugs/QoL with guest pass terminals

code/__defines/planets.dm, code/modules/planet/sif.dm
=> [ЗЕРКАЛО] [MIRROR] Adds fog as a weather. It's cold.

code/game/objects/random/mapping.dm, code/game/objects/random/misc_vr.dm, code/game/objects/structures/crates_lockers/_closets_appearance_definitions.dm, code/game/objects/structures/crates_lockers/crates.dm, maps/offmap_vr/talon/talon_v2.dm
=> [ЗЕРКАЛО] Frozen Organ Crates

code/game/objects/micro_structures.dm, code/game/objects/structures/ghost_pods/event_vr.dm, code/game/turfs/flooring/seasonal.dm, code/modules/mob/living/simple_mob/subtypes/animal/alien animals/catslug.dm, code/modules/mob/living/simple_mob/subtypes/animal/alien animals/teppi.dm, code/modules/mob/living/simple_mob/subtypes/animal/squirrel.dm, code/modules/mob/living/simple_mob/subtypes/vore/morph/morph.dm
=> [ЗЕРКАЛО] Mob tweaks and fixes

code/game/objects/structures/props/prop.dm
=> [ЗЕРКАЛО] Should fix props being un-var-editable

code/game/area/areas.dm, maps/expedition_vr/aerostat/_aerostat_science_outpost.dm
=> [ЗЕРКАЛО] Fixes ambience runtime

maps/stellar_delight/stellar_delight2.dmm
=> [ЗЕРКАЛО] Fixes missing trunk under a resleeving disposal unit

code/_helpers/global_lists_vr.dm
=> [ЗЕРКАЛО] Adds a mob to gold extract pool

code/modules/mob/living/carbon/human/species/species_vr.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
=> [ЗЕРКАЛО] fixes trait prefs not working and makes a trait pref for stuffing feeder

code/modules/mob/living/carbon/human/species/station/prommie_blob.dm
=> [ЗЕРКАЛО] Fixes item loss when dying as a prommie blob

code/modules/client/preference_setup/loadout/loadout_utility.dm
=> [ЗЕРКАЛО] Fixes lore codex name

code/modules/mob/living/carbon/human/species/species_vr.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm, code/modules/reagents/reagents/dispenser.dm, code/modules/reagents/reagents/food_drinks.dm, code/modules/reagents/reagents/food_drinks_vr.dm
=> [ЗЕРКАЛО] Ethanol Processors

maps/tether/tether-05-station1.dmm
=> [ЗЕРКАЛО] Fixes the securiship.

code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/prometheans.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/station_special_vr.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
=> [ЗЕРКАЛО] Adds Firm Body trait and throwforce resistance

code/modules/client/preference_setup/general/05_background.dm, code/modules/client/preference_setup/general/06_flavor.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/silicon/silicon.dm
=> [ЗЕРКАЛО] Stop 'cancel' button from wiping flavor text

code/modules/mob/living/simple_mob/subtypes/vore/rat.dm, maps/tether/tether-01-surface1.dmm
=> [ЗЕРКАЛО] Makes the tether trash rat into real boy/girl/creature

code/modules/mob/living/silicon/robot/life.dm
=> [ЗЕРКАЛО] Makes borgs not stunned when weakened

vorestation.dme
=> [ЗЕРКАЛО] I ship it

code/modules/mob/dead/corpse.dm, code/modules/mob/dead/corpse_vr.dm, code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs_vr.dm, code/modules/organs/organ_external_vr.dm
=> [ЗЕРКАЛО] Adds 'drone' versions of mercenary mobs.

code/modules/food/food/cans.dm, code/modules/food/food/drinks.dm
=> [ЗЕРКАЛО] A Very Serious PR

code/modules/hydroponics/trays/tray.dm
=> [ЗЕРКАЛО] Botany/Hydroponics minifix

code/game/objects/structures/ghost_pods/antagonist.dm
=> [ЗЕРКАЛО] Makes xeno egg ghost pods anchored

code/modules/power/singularity/containment_field.dm, code/modules/power/singularity/field_generator.dm
=> [ЗЕРКАЛО] Field Generators Glow!

code/modules/clothing/head/misc_vr.dm
=> [ЗЕРКАЛО] Fixes pizza guy visor

code/modules/clothing/glasses/hud_vr.dm
=> [ЗЕРКАЛО] Adds verb to AR glasses to toggle vision planes

code/modules/client/preference_setup/loadout/loadout_fluffitems_vr.dm, code/modules/vore/fluffstuff/custom_items_vr.dm
=> [ЗЕРКАЛО] Adds Mira's health services medal

code/modules/overmap/sectors.dm
=> [ЗЕРКАЛО] Adjusts sectors to have real_icons

maps/groundbase/gb-z2.dmm, maps/groundbase/gb-z3.dmm, maps/groundbase/groundbase_areas.dm
=> [ЗЕРКАЛО] Rascal's Pass tweaks

code/modules/client/preference_setup/general/02_language.dm, code/modules/client/preference_setup/vore/03_egg.dm, code/modules/mob/living/carbon/human/login.dm, code/modules/mob/new_player/new_player.dm, code/modules/resleeving/autoresleever.dm, code/modules/vore/eating/inbelly_spawn.dm
=> [ЗЕРКАЛО] Preferred Language + Autohiss Default Options

code/modules/mob/living/simple_mob/simple_mob.dm, code/modules/mob/living/simple_mob/subtypes/animal/alien animals/catslug.dm, code/modules/ventcrawl/ventcrawl.dm
=> [ЗЕРКАЛО] Fixes simple_mob ID giving system

code/modules/mob/living/simple_mob/combat.dm, code/modules/mob/living/simple_mob/simple_mob.dm, code/modules/tension/tension.dm
=> [ЗЕРКАЛО] Simplemob Injury System

maps/tether/tether-05-station1.dmm
=> [ЗЕРКАЛО] Tether Map Changes

.vscode/tasks.json
=> [ЗЕРКАЛО] Adds PrettyBuild to Tasks for VSCode

maps/groundbase/gb-z1.dmm, maps/groundbase/gb-z2.dmm
=> [ЗЕРКАЛО] RP General Map Updates

code/modules/reagents/reagents/food_drinks.dm
=> [ЗЕРКАЛО] Update food_drinks.dm

code/modules/reagents/reactions/instant/instant_vr.dm, code/modules/reagents/reagents/medicine_vr.dm
=> [ЗЕРКАЛО] Lipozine Plus

SECURITY.md
=> [ЗЕРКАЛО] Create SECURITY.md

maps/groundbase/gb-z1.dmm, maps/groundbase/gb-z2.dmm
=> [ЗЕРКАЛО] RP-Map-Adjustments-Addendum

maps/submaps/engine_submaps_vr/tether/engine_rust.dmm, maps/submaps/engine_submaps_vr/tether/engine_singulo.dmm, maps/submaps/engine_submaps_vr/tether/engine_sme.dmm, maps/submaps/engine_submaps_vr/tether/engine_tesla.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-05-station1.dmm, maps/tether/tether-07-solars.dmm
=> [ЗЕРКАЛО] Anomalous R-window Cleanup

code/game/objects/items/weapons/stunbaton.dm
=> [ЗЕРКАЛО] Stunbaton Tweaks

code/__defines/species_languages.dm, code/modules/mob/living/carbon/human/species/station/traits_vr/neutral.dm, code/modules/reagents/reagents/food_drinks.dm
=> [ЗЕРКАЛО] Chocolate Allergy

code/modules/recycling/conveyor2.dm, maps/tether/tether-05-station1.dmm
=> [ЗЕРКАЛО] One-way conveyor switches

code/modules/food/food/snacks.dm
=> [ЗЕРКАЛО] Actual Chocolate in donuts

code/modules/projectiles/ammunition/rounds.dm, code/modules/projectiles/projectile/scatter.dm
=> [ЗЕРКАЛО] Shotgun Tweak

code/modules/clothing/under/altevian_vr.dm
=> [ЗЕРКАЛО] Altevian Clothing Fix

code/modules/nifsoft/software/05_health.dm
=> [ЗЕРКАЛО] Make synth medicines tell medical you are dying

code/game/objects/items/weapons/id cards/syndicate_ids.dm
=> [ЗЕРКАЛО] Agent ID Feedback
